[build]
  publish = "/"

[[headers]]
  for = "/gallery.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.enc"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
