// 同步时间：2024年12月29日
// 源码地址：https://github.com/ikechan8370/yunzai-meme/blob/main/meme.js

import plugin from '../../../lib/plugins/plugin.js';
import fetch, { File, FormData } from 'node-fetch'
import fs from 'fs'
import path from 'node:path'
import _ from 'lodash'
import loader from '../../../lib/plugins/loader.js'
import { Config } from '../utils/config.js'
import { buildMemeListData } from '../utils/memeCategory.js'
import {
  hidePrivacyInfo,
  getUserDetailedInfo,
} from '../utils/paimonFuction.js'

if (!global.segment) {
  global.segment = (await import('oicq')).segment
}
const baseUrl = Config.meme_baseUrl
/**
 * 机器人发表情是否引用回复用户
 * @type {boolean}
 */
const reply = Config.meme_reply
/**
 * 是否强制使用#触发命令
 */
const forceSharp = Config.meme_forceSharp
/**
 * 主人保护，撅主人时会被反撅 (暂时只支持QQ)
 * @type {boolean}
 */
const masterProtectDo = Config.meme_masterProtectDo
/**
 * 用户输入的图片，最大支持的文件大小，单位为MB
 * @type {number}
 */
const maxFileSize = Config.meme_maxFileSize

let keyMap = {}

let infos = {}

/**
 * 刷新串行队列（互斥）。
 *
 * 必须是模块级：`keyMap`/`infos` 本身就是模块级全局，互斥只有和它们同作用域才成立。
 * 没有它时两个 init() 会并发跑——后一次手里握的是**启动时的旧快照**，它一旦走回退分支
 * 就把前一次刚提交的新数据覆盖回旧版本，还会把旧规则重新写回 loader。
 * 手动 `#表情包更新` 撞上凌晨定时任务即可复现。
 * @type {Promise<unknown>}
 */
let refreshChain = Promise.resolve()

/**
 * 主人保护list 如['lash','do','beat_up','little_do']
 */
let protectList = ['lash', 'do', 'beat_up', 'little_do', 'fast_do', 'qi', 'fast_qi']

/**
 * meme 使用计数 Redis key 前缀
 */
const MEME_USAGE_REDIS_PREFIX = 'Yz:paimon_meme_usage:'

/**
 * meme 数据缓存文件。
 *
 * infos 与 keyMap **存在同一个文件里**：跨代缓存（infos 是新的、keyMap 是旧的）是这对数据最现实的
 * 事故源——两个独立 `writeFileSync` 之间进程退出就会产生这种组合，而两份都非空又都自洽时会绕过
 * 远端拉取、又在校验阶段被整批丢弃，插件只剩基础命令。合成一个文件后这种组合在结构上不可能出现。
 */
const MEME_CACHE_FILE = 'data/memes/dataset.json'

/** 旧版双文件缓存。只用于一次性迁移，见 `migrateLegacyDataset()` */
const LEGACY_INFOS_FILE = 'data/memes/infos.json'
const LEGACY_KEYMAP_FILE = 'data/memes/keyMap.json'

/** 缓存格式版本，将来改结构时用它判断旧文件能不能直接读 */
const MEME_CACHE_VERSION = 1

/**
 * 列表图缓存文件名 —— 把 `meme_forceSharp` 编进身份。
 *
 * 图上写着"发送 #关键词"还是"直接发送关键词"，这个配置一变，图就必须换一张。
 * 只靠「24h 缓存 + 更新成功时清缓存」是不够的：改配置重启后 dataset 走本地缓存
 * （`refreshed=false`），不会触发清理，于是最长 24h 内列表图还在教用户发一个已经失效的格式。
 * 把身份编进文件名后，配置一变自然就换文件，不需要依赖任何清理时机。
 */
const listCacheFile = () => `data/memes/render_list${Config.meme_forceSharp ? '_sharp' : '_plain'}.jpg`

/** 清理列表图缓存时要一起删掉的候选（含旧版固定名，升级后会残留） */
const LIST_CACHE_FILES = [
  'data/memes/render_list_sharp.jpg',
  'data/memes/render_list_plain.jpg',
  'data/memes/render_list.jpg',
]

/** 逐项重建的并发 worker 数。串行 971 次请求按平均 150ms 要 ~146s，全量并发又会打爆后端 */
const REBUILD_CONCURRENCY = 12

/** 逐项重建里单个 `/info` 的额外重试次数（单条失败会让整批作废，值得重试） */
const REBUILD_ITEM_RETRIES = 2

/**
 * 列表图的渲染宽度（px）。
 *
 * 图片的最终宽度就等于它：puppeteer 截取的是 `#container` 元素，元素多宽图就多宽，
 * 所以想要 2K / 4K 改这里即可，不需要去动 deviceScaleFactor（那属于渲染器全局配置）。
 * 971 个表情排下来是张长图，宽度给到 2560 能在"看得清"和"体积可控"之间取平衡。
 */
const MEME_LIST_WIDTH = 2560

/** 列表图 JPEG 质量。长图给太高体积会失控，86 在肉眼无感的前提下能省掉一大半 */
const MEME_LIST_QUALITY = 86

/** 列表图分组方案，可选值见 utils/memeCategory.js 的 SUPPORTED_SCHEMES */
const MEME_LIST_SCHEME = 'hybrid'

/** 使用次数达到该值，列表图上给该表情打「热」标 */
const MEME_LIST_HOT_THRESHOLD = 30

/** 多少天内创建的表情打「新」标 */
const MEME_LIST_NEW_DAYS = 30

/**
 * 列表图使用的模板（相对 `resources/`，不带 .html）。
 * 换审美只需改这一行，模板之间共用同一份 `buildMemeListData()` 数据契约。
 */
const MEME_LIST_TEMPLATE = 'memeList/index'

/**
 * 本插件在云崽插件加载器中的 key（file.name）后缀，用于定位已注册的插件条目
 */
const PLUGIN_FILE_NAME = '派蒙meme.js'

/**
 * 命令前缀：forceSharp 开启时强制要求 `#`。
 * 基础命令与 meme 关键词命令共用同一套前缀，避免"开了强制 # 但 `meme列表` 仍能不带 # 触发"的不一致
 */
const cmdReg = body => new RegExp(`${forceSharp ? '^#' : '^#?'}${body}`)

/**
 * 基础命令规则（不依赖 keyMap，插件加载后即生效）
 */
const baseRules = () => [
  { /** 命令正则匹配 */ reg: cmdReg('(meme(s)?|表情包)列表$'), /** 执行方法 */ fnc: 'memesList' },
  { reg: cmdReg('随机(meme(s)?|表情包)'), fnc: 'randomMemes' },
  { reg: cmdReg('(meme(s)?|表情包)帮助'), fnc: 'memesHelp' },
  { reg: cmdReg('(meme(s)?|表情包)搜索'), fnc: 'memesSearch' },
  { reg: cmdReg('(meme(s)?|表情包)更新'), fnc: 'memesUpdate', permission: 'master' }
]

/**
 * 依据当前 keyMap 生成 meme 关键词规则
 *
 * 关键词必须按**字面量**匹配：`memes()` 内部是用 `msg.startsWith(k)` 找目标的。
 * 不转义的话，含 `(` `[` `\` 的关键词会让 `new RegExp` 直接抛错（整批规则构造失败），
 * 含 `.` `+` `*` 的会误匹配（如 `a.b` 命中 `aXb`，而 `memes()` 又按字面量找不到 → 后续取 info 报错）。
 * @returns {Array<{reg: RegExp, fnc: string}>}
 */
const memeKeyRules = () =>
  Object.keys(keyMap).map(key => ({
    /** 命令正则匹配 */
    reg: cmdReg(_.escapeRegExp(key)),
    /** 执行方法 */
    fnc: 'memes'
  }))

export class memes extends plugin {
  constructor() {
    let option = {
      /** 功能名称 */
      name: '派蒙meme表情制作',
      /** 功能描述 */
      dsc: '派蒙meme表情制作',
      /** https://oicqjs.github.io/oicq/#events */
      event: 'message',
      /** 优先级，数字越小等级越高 */
      priority: 5000,
      /** 基础规则 + 当前已加载到的 meme 关键词规则 */
      rule: [...baseRules(), ...memeKeyRules()]
    }

    super(option)

    // generated by ChatGPT
    function generateCronExpression() {
      // 生成每天的半夜2-4点之间的小时值（随机选择）
      const hour = Math.floor(Math.random() * 3) + 2

      // 生成每小时的随机分钟值（0到59之间的随机数）
      const minute = Math.floor(Math.random() * 60)

      // 构建 cron 表达式
      return `${minute} ${hour} * * *`
    }

    this.task = {
      // 每天的凌晨3点执行
      cron: generateCronExpression(),
      name: 'memes自动更新任务',
      /** 传 true 表示忽略本地缓存，强制拉取远端（否则定时任务只会把本地缓存重新读一遍，等于空转） */
      fnc: this.init.bind(this, true)
    }
  }

  /**
   * 初始化 / 更新 meme 资源，并把最新规则同步到插件加载器。
   *
   * **并发语义**：调用会排队串行执行。`keyMap`/`infos` 是模块级全局，两次刷新并发时后一次手里
   * 握的是启动时的旧快照，一旦走回退分支就会把前一次刚提交的新数据覆盖回旧版本。
   * 这里刻意用"排队"而不是"并发时复用同一次结果"——复用会把 force 语义吃掉，
   * 手动 `#表情包更新` 会拿到一次"其实没拉远端"的结果而误报更新失败。
   *
   * **数据语义**：整次拉取在局部变量里完成，只有拿到一份完整且通过 `validateMemeDataset()`
   * 的数据才一次性替换全局（原子提交）。旧实现一进来就清空全局再去 await 网络，
   * 而加载器里旧关键词规则仍然生效，更新期间命中旧关键词就会拿到空 keyMap / undefined info 直接报错。
   *
   * @param {boolean} force true 时忽略本地缓存强制拉取远端，用于手动更新与定时任务
   * @returns {Promise<{ refreshed: boolean, keys: number, fallback: boolean, persisted: boolean }>}
   *          refreshed: 本次是否拿到可用的远端数据；keys: 最终生效的关键词数量；
   *          fallback: 拉取失败后是否沿用了更新前的数据
   */
  async init(force = false) {
    const run = refreshChain.then(
      () => this.doRefresh(force),
      // 上一次失败也要继续排队执行，否则链断在这里、后续刷新永远不跑
      () => this.doRefresh(force)
    )
    // 队列上挂一个永不 reject 的版本，避免一次失败污染整条链
    refreshChain = run.then(() => {}, () => {})
    return await run
  }

  /**
   * 真正执行一次刷新。只应由 `init()` 通过串行队列调用。
   * @param {boolean} force
   * @returns {Promise<{ refreshed: boolean, keys: number, fallback: boolean, persisted: boolean }>}
   */
  async doRefresh(force) {
    mkdirs('data/memes')
    /** 更新前的数据，拉取失败时用于回退 */
    const oldKeyMap = keyMap
    const oldInfos = infos

    /** 本次结果先落局部变量，校验通过才替换全局 */
    let nextInfos = {}
    let nextKeyMap = {}
    /**
     * 是否真的从远端取到了数据并被采纳（区别于"只是读了本地缓存"）。
     * 只在远端赋值处置真，否则插件每次启动都会误报"更新完成"并清掉列表图缓存。
     */
    let fetched = false

    if (force) {
      // 强制刷新：跳过本地缓存，让下面的远端拉取分支一定执行
      logger.mark('yunzai-meme 强制更新：忽略本地缓存，直接拉取远端')
    } else {
      // 插件加载：优先用本地缓存，避免启动被远端拖慢。
      // 缓存本身也要过校验：残缺/跨版本时返回 null，下面的拉取分支会补上（这就是自愈）
      const cached = loadMemeDataset()
      if (cached) {
        nextInfos = cached.infos
        nextKeyMap = cached.keyMap
      }
    }

    // 远端拉取失败不应阻塞插件加载（HF Space 等已下线时这里会全失败）
    try {
      if (!baseUrl) {
        throw new Error('meme_baseUrl 未配置')
      }
      // /memes/static/infos.json、keyMap.json 只是可选加速，不是上游 meme-generator 的接口：
      // 上游 app.py 只有 /memes/keys、/memes/<key>/info、/memes/render_list 等，直连会 404；
      // 只有少数部署额外加了这层聚合（如 qwqcc HF Space 的 bootstrap.py 动态生成）。
      // 所以拿不到时必须保底重建（见下方逐项重建分支）。
      if (Object.keys(nextInfos).length === 0) {
        logger.mark('yunzai-meme infos资源本地不存在，正在远程拉取中')
        const data = await fetchJsonWithRetry(`${baseUrl}/memes/static/infos.json`)
        // 远端数据一律不信：先归一化再采纳（空关键词会变成劫持消息路由的规则）
        const sanitized = sanitizeInfos(data)
        if (Object.keys(sanitized).length) {
          nextInfos = sanitized
          fetched = true
        }
      }
      if (Object.keys(nextKeyMap).length === 0) {
        logger.mark('yunzai-meme keyMap资源本地不存在，正在远程拉取中')
        const data = await fetchJsonWithRetry(`${baseUrl}/memes/static/keyMap.json`)
        const sanitized = sanitizeKeyMap(data)
        if (Object.keys(sanitized).length) {
          nextKeyMap = sanitized
          fetched = true
        }
      }

      // 两个都拿到了就**先校验**：pair 不合法等同于"没拉到"，必须一起丢掉去重建。
      // 只按"空不空"决定要不要重建是不够的——两个文件都非空但彼此不一致时不会进重建分支，
      // 一路走到最后才发现不合法，冷启动时没有旧数据兜底，整套 meme 直接空掉
      if (Object.keys(nextInfos).length && Object.keys(nextKeyMap).length) {
        const staticVerdict = validateMemeDataset(nextInfos, nextKeyMap)
        if (!staticVerdict.ok) {
          logger.warn(`[meme] 静态资源不可用（${staticVerdict.reason}），丢弃后转逐项重建`)
          nextInfos = {}
          nextKeyMap = {}
          fetched = false
        }
      }

      if (Object.keys(nextInfos).length === 0 || Object.keys(nextKeyMap).length === 0) {
        // 两个静态资源拿不齐，才退回逐项重建
        logger.warn('[meme] 静态资源拉取失败（判断为原生 meme 生成器），切换为逐项重建兜底：从 /memes/keys 取 key 列表，再并发拉取 /memes/<key>/info 重建 keyMap 与 infos')
        const keys = await fetchJsonWithRetry(`${baseUrl}/memes/keys`)
        if (Array.isArray(keys) && keys.length) {
          const rebuilt = await rebuildFromKeys(keys)
          if (rebuilt) {
            nextInfos = rebuilt.infos
            nextKeyMap = rebuilt.keyMap
            fetched = true
          }
        }
      }
    } catch (err) {
      // node-fetch 的网络错误会把完整请求 URL 拼进 message（`request to http://<ip>:<port>/… failed`），
      // 所以这里必须过一遍 hidePrivacyInfo，否则日志里会留下部署机 IP
      logger.warn('[meme] 远程拉取 meme 资源失败，插件仍可加载但功能将不可用:', hidePrivacyInfo(err.message))
    }

    const verdict = validateMemeDataset(nextInfos, nextKeyMap)
    const usable = verdict.ok
    if (!usable && (Object.keys(nextInfos).length > 0 || Object.keys(nextKeyMap).length > 0)) {
      logger.warn(`[meme] 本次数据不可用（${verdict.reason}），放弃本次结果`)
    }

    const refreshed = usable && fetched
    let fallback = false
    /**
     * 本次"该落盘的东西"是否落盘成功。写盘失败不影响运行期数据（不回滚），
     * 但重启后会恢复到旧数据，所以调用方要知道。没有需要落盘的数据时保持 true
     */
    let persisted = true
    if (usable) {
      // 原子替换：命令处理读到的要么是旧数据、要么是新数据，不会是半套
      infos = nextInfos
      keyMap = nextKeyMap
      // 只有真的从远端拉到才落盘，避免把"刚读出来的缓存"原样再写回去
      if (fetched) persisted = saveMemeDataset(infos, keyMap)
    } else if (Object.keys(oldKeyMap).length > 0) {
      // 没拿到可用数据时沿用更新前的数据，别把正在用的 meme 全部弄没
      infos = oldInfos
      keyMap = oldKeyMap
      fallback = true
      logger.warn('[meme] 未取到新数据，继续沿用更新前的 meme 资源')
    } else {
      // 冷启动且拉取失败：保持空，规则交给 registerRules 兜底
      infos = {}
      keyMap = {}
    }

    if (refreshed) {
      // 数据变了，列表图（24h 缓存）也该重渲染
      this.clearRenderListCache()
      logger.mark(`[meme] 更新完成，共 ${Object.keys(keyMap).length} 个 meme 关键词`)
    }

    // 手动/自动更新都会走到这里：把最新规则同步回加载器，免重启生效
    this.registerRules()

    return { refreshed, keys: Object.keys(keyMap).length, fallback, persisted }
  }

  /** 清理 meme 列表图缓存（memesList 的 24h 缓存），下次查看时重新渲染。
   *  三种文件名都删：列表图会把 `meme_forceSharp` 编进文件名，只删当前那一种会留下另一种身份的旧图 */
  clearRenderListCache() {
    for (const file of LIST_CACHE_FILES) {
      if (!fs.existsSync(file)) continue
      try {
        fs.unlinkSync(file)
      } catch (err) {
        logger.warn('[meme] 清理列表图缓存失败:', err.message)
      }
    }
  }

  /**
   * 生成当前应生效的完整规则（基础规则 + keyMap 关键词规则）
   * @returns {Array<{reg: RegExp, fnc: string, permission?: string}>}
   */
  getRules() {
    return [...baseRules(), ...memeKeyRules()].map(rule => ({
      ...rule,
      reg: rule.reg instanceof RegExp ? rule.reg : new RegExp(rule.reg)
    }))
  }

  /**
   * 把最新规则注册/更新到云崽插件加载器
   *
   * `PluginsLoader.deal()` 匹配命令时读取的是 loader.priority 里**注册实例**的 rule，
   * 每次消息执行时 new 出来的实例只是副本，改副本的 rule 不生效，
   * 所以必须回写注册条目，才能在 init()（手动 #meme更新 / 定时任务自动更新）之后立即生效。
   *
   * 插件加载阶段调用 init() 时本插件尚未 push 进 priority，此时匹配不到条目属正常情况，
   * 随后的注册实例会由构造函数按当时已就绪的 keyMap 生成规则。
   * @returns {number} 被同步的注册条目数
   */
  registerRules() {
    if (Object.keys(keyMap).length === 0) {
      // 远端拉取失败时不要清空规则，保留旧规则继续可用
      logger.warn('[meme] keyMap 为空，跳过规则同步，保留原有 meme 命令')
      return 0
    }

    const rules = this.getRules()
    this.rule = rules

    const entries = loader.priority.filter(
      i => i.class === memes || (typeof i.key === 'string' && i.key.endsWith(PLUGIN_FILE_NAME))
    )
    for (const entry of entries) {
      if (!entry.plugin) continue
      entry.plugin.rule = rules
    }

    if (entries.length) {
      logger.mark(`[meme] 已动态注册 ${Object.keys(keyMap).length} 个 meme 关键词规则`)
    } else {
      logger.debug('[meme] 插件尚未注册到加载器，规则将由注册时的构造函数生成')
    }
    return entries.length
  }

  async memesUpdate(e) {
    await e.reply('yunzai-memes更新中')
    let result
    try {
      // 强制刷新，不再依赖「先删缓存文件」来触发远端拉取
      result = await this.init(true)
    } catch (err) {
      await e.reply('更新失败：' + hidePrivacyInfo(err.message))
      return
    }
    if (result.fallback) {
      await e.reply(`更新失败：未拉取到新资源，继续沿用原有 ${result.keys} 个 meme 规则`)
    } else if (!result.refreshed) {
      await e.reply('更新失败：未拉取到 meme 资源，已保留原有规则')
    } else if (result.persisted === false) {
      // 运行期数据已经更新成功，但落盘失败——重启后会回到旧数据，必须说清楚
      await e.reply(`已注册 ${result.keys} 个 meme 规则，但本地缓存写入失败；重启后可能恢复旧数据`)
    } else {
      await e.reply(`更新完成，已注册 ${result.keys} 个 meme 规则`)
    }
  }

  async memesHelp(e) {
    if (Config.meme_turnOff) return false;
    e.reply('【memes列表】：查看支持的memes列表\n【{表情名称}】：memes列表中的表情名称，根据提供的文字或图片制作表情包\n【随机meme】：随机制作一些表情包\n【meme搜索+关键词】：搜索表情包关键词\n【{表情名称}+详情】：查看该表情所支持的参数')
  }

  async memesSearch(e) {
    if (Config.meme_turnOff) return false;
    let search = e.msg.replace(/^#?(meme(s)?|表情包)搜索/, '').trim()
    if (!search) {
      await e.reply('你要搜什么？')
      return true
    }
    let hits = Object.keys(keyMap).filter(k => k.indexOf(search) > -1)
    let result = '搜索结果'
    if (hits.length > 0) {
      for (let i = 0; i < hits.length; i++) {
        result += `\n${i + 1}. ${hits[i]}`
      }
    } else {
      result += '\n无'
    }
    await e.reply(result, e.isGroup)
  }

  async memesList(e) {
    if (Config.meme_turnOff) return false

    const resultFileLoc = listCacheFile()
    const cacheMaxAge = 24 * 60 * 60 * 1000 // 24小时缓存

    // 检查缓存是否有效
    if (fs.existsSync(resultFileLoc)) {
      const stats = fs.statSync(resultFileLoc)
      if (Date.now() - stats.mtimeMs < cacheMaxAge) {
        await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`))
        return true
      }
    }

    // 本地模板渲染：按分组排版，宽度与质量见本文件顶部的 MEME_LIST_* 常量
    if (await this.renderMemeListLocal(e, resultFileLoc)) {
      await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`))
      return true
    }

    // 本地渲染不可用（没装 Chromium 等）时退回远端 render_list，
    // 否则这些环境下 #meme列表 会整个失联
    return await this.renderMemeListRemote(e, resultFileLoc)
  }

  /**
   * 用本地 HTML 模板渲染分组列表图。
   *
   * 图片由渲染器按 `path` 参数直接写进 resultFileLoc，省掉一次 base64 往返；
   * 调用方只需确认文件真的存在，就能用与缓存命中相同的路径发图。
   *
   * @param {object} e
   * @param {string} resultFileLoc 相对 cwd 的图片路径
   * @returns {Promise<boolean>} 是否渲染成功
   */
  async renderMemeListLocal(e, resultFileLoc) {
    if (Object.keys(infos).length === 0) {
      logger.warn('[meme] infos 为空，跳过本地列表图渲染')
      return false
    }
    try {
      // 惰性 import：utils/common.js 会拉起 puppeteer / tts / pdfjs 一整条重依赖链，
      // 而 meme 的其它命令都不需要它，测试套件也不该因此被迫加载框架
      const { render } = await import('../utils/common.js')

      const usageCounts = await this.getMemeUsageCounts(Object.keys(infos))
      const { groups, stats } = buildMemeListData(infos, {
        scheme: MEME_LIST_SCHEME,
        usageCounts,
        hotThreshold: MEME_LIST_HOT_THRESHOLD,
        newThresholdDays: MEME_LIST_NEW_DAYS
      })

      // 渲染器按相对 cwd 的路径写盘，目录不存在会直接失败
      mkdirs('data/memes')
      // 先清掉上一轮留下的过期文件：否则渲染静默失败时 existsSync 会把旧图误判成新产物
      if (fs.existsSync(resultFileLoc)) fs.unlinkSync(resultFileLoc)

      // 刻意不往图上放 meme_baseUrl 与生成时间：前者会把部署机 IP 印到群里（图会被转发、存档），
      // 后者对使用者没有价值。模板里的 sourceHost / generatedAt 已一并移除
      await render(e, 'chatgpt-plugin', MEME_LIST_TEMPLATE, {
        width: MEME_LIST_WIDTH,
        groups,
        stats,
        // 列表图必须跟命令前缀保持一致：开了强制 # 却让图上写着裸关键词，用户照抄会一条都触发不了
        forceSharp: !!Config.meme_forceSharp,
        pageClass: Config.meme_forceSharp ? 'force-sharp' : '',
        imgType: 'jpeg',
        quality: MEME_LIST_QUALITY,
        path: resultFileLoc
      }, { retType: 'base64' })

      if (!fs.existsSync(resultFileLoc)) {
        logger.warn('[meme] 本地列表图渲染完成但文件未落盘')
        return false
      }

      const size = fs.statSync(resultFileLoc).size
      logger.mark(
        `[meme] 本地列表图渲染完成：${groups.length} 个分组 / ${stats.totalMemes} 个表情 / ${(size / 1024 / 1024).toFixed(2)}MB`
      )
      return true
    } catch (err) {
      logger.error('[meme] 本地列表图渲染失败，将退回远端渲染:', hidePrivacyInfo(err.message))
      return false
    }
  }

  /**
   * 旧版行为：请求远端 meme-generator 的 render_list 出图。
   * 仅作为本地渲染不可用时的兜底，逻辑保持原样。
   * @param {object} e
   * @param {string} resultFileLoc
   * @returns {Promise<boolean>}
   */
  async renderMemeListRemote(e, resultFileLoc) {
    try {
      // 构建带标签和排序的 meme 列表
      const memeList = await this.buildMemeListWithLabels()

      const response = await fetch(`${baseUrl}/memes/render_list`, {
        method: 'POST',
        // 这个接口回的是图片而不是 JSON，别声明 Accept: application/json
        headers: {
          'Content-Type': 'application/json',
          Accept: 'image/*'
        },
        body: JSON.stringify({
          meme_list: memeList,
          text_template: '{keywords}',
          add_category_icon: true
        }),
        signal: timeoutSignal(MEME_RENDER_TIMEOUT)
      })

      if (!response.ok) {
        logger.error('[meme] render_list 请求失败:', response.status)
        return false
      }

      // 200 不代表是图片：反代 / WAF / 登录页会返回 HTML 错页，不校验的话会被正式写成
      // render_list_*.jpg 并缓存 24h，之后每次看列表都是那张错页
      const listType = response.headers.get('content-type') || ''
      if (!listType.startsWith('image/')) {
        const peek = await response.text()
        logger.error(
          `[meme] render_list 返回的不是图片(${listType || '空'})，放弃远端渲染:`,
          hidePrivacyInfo(peek.slice(0, 300))
        )
        return false
      }

      const resultBlob = await response.blob()
      const resultBuffer = Buffer.from(await resultBlob.arrayBuffer())
      mkdirs('data/memes')
      fs.writeFileSync(resultFileLoc, resultBuffer)
      await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`))
      return true
    } catch (err) {
      logger.error('[meme] 远端列表图渲染也失败:', hidePrivacyInfo(err.message))
      return false
    }
  }

  /**
   * 构建带标签的 meme 列表（按创建时间倒序,便于观察新增的表情）
   * - new: 最近30天内创建
   * - hot: 期限内使用超过30次
   * @returns {Promise<Array<{meme_key: string, disabled: boolean, labels: string[]}>>}
   */
  async buildMemeListWithLabels() {
    // 复用顶部常量，别在这里另写一份：数值目前一样，但改了 MEME_LIST_* 就会和本地列表图
    // 出现两套 new/hot 判定（本地走 buildMemeGroups，远端兜底走这里）
    const NEW_THRESHOLD_MS = MEME_LIST_NEW_DAYS * 24 * 60 * 60 * 1000
    const HOT_THRESHOLD = MEME_LIST_HOT_THRESHOLD
    const now = Date.now()

    // 批量获取所有 meme 的使用计数
    const memeKeys = Object.keys(infos)
    const usageCounts = await this.getMemeUsageCounts(memeKeys)

    return Object.entries(infos)
      .map(([key, info]) => {
        const createdTime = new Date(info.date_created).getTime()
        const labels = []

        // 时间要落在 [0, now] 才算"新"：只判 `now - createdTime < 阈值` 的话，
        // 上游给了未来时间（负差值当然小于阈值）也会被标成 new
        const validTime = Number.isFinite(createdTime) && createdTime > 0 && createdTime <= now
        if (validTime && (now - createdTime) < NEW_THRESHOLD_MS) labels.push('new')
        if ((usageCounts[key] || 0) >= HOT_THRESHOLD) labels.push('hot')

        return { meme_key: key, disabled: false, labels, _sortKey: validTime ? createdTime : 0 }
      })
      .sort((a, b) => b._sortKey - a._sortKey)
      .map(({ meme_key, disabled, labels }) => ({ meme_key, disabled, labels }))
  }

  /**
   * 批量获取 meme 使用计数（只返回有使用记录的）
   * @param {string[]} memeKeys - meme key 列表
   * @returns {Promise<Record<string, number>>} - { meme_key: count }（仅包含 count > 0 的）
   */
  async getMemeUsageCounts(memeKeys) {
    const counts = {}

    if (memeKeys.length === 0) return counts

    const redisKeys = memeKeys.map(key => `${MEME_USAGE_REDIS_PREFIX}${key}`)
    try {
      const results = await redis.mGet(redisKeys)
      memeKeys.forEach((key, index) => {
        const count = parseInt(results[index]) || 0
        if (count > 0) counts[key] = count  // 只存非零值
      })
    } catch (err) {
      logger.warn('[meme] 批量获取使用计数失败:', err.message)
    }

    return counts
  }

  /**
   * 记录 meme 使用次数。
   *
   * INCR 与 EXPIRE 必须放进同一个 MULTI/EXEC：拆成两条命令时，若在两者之间断连，会留下一个
   * **没有 TTL** 的计数 key，永久占位（AGENTS 里明确禁止 INCR+EXPIRE 两步写法）。
   *
   * 语义说明：这是"3 天不活跃才清零的连续累计值"，**不是滚动 3 天窗口**。某张 meme 只要每 2 天
   * 被用一次，计数就会一直累加。所以「热」表达的是"最近活跃且长期高频"，不是"近 3 天用满 30 次"。
   * @param {string} memeKey - meme 的 key
   */
  async recordMemeUsage(memeKey) {
    const REDIS_KEY = `${MEME_USAGE_REDIS_PREFIX}${memeKey}`
    const EXPIRE_SECONDS = 3 * 24 * 60 * 60 // 3天
    await redis.multi().incr(REDIS_KEY).expire(REDIS_KEY, EXPIRE_SECONDS).exec()
  }

  /**
   * @description: 
   * @param {*} e
   * @param {*} isDeleteUnharmoniousKeys 是否删除的不和谐的 keys，默认为 false;
   * @return {*}
   */
  async randomMemes(e, isDeleteUnharmoniousKeys = false) {
    if (Config.meme_turnOff) return false;
    // 必须排除没有可用关键词的条目：normalizeKeywords 会有意留下 `keywords: []` 的 info，
    // 一旦抽中就会 `e.msg = undefined`，下一层第一批逻辑 `e.msg.replace(...)` 直接炸
    let keys = Object.keys(infos).filter(key =>
      infos[key].params_type.min_images === 1 &&
      infos[key].params_type.min_texts === 0 &&
      (infos[key].keywords || []).length > 0
    )
    if (isDeleteUnharmoniousKeys) {
      /** 需要删除的不和谐的 keys */
      const keys_delete = ['behead', 'tomb_yeah', 'shishilani', 'thump_wildly', 'clown', 'taunt', 'mourning', 'rise_dead'];
      keys = keys.filter(key => !keys_delete.includes(key));
    }
    if (!keys.length) {
      // 远端数据没拉到、或某个版本里没有"只要一张图"的 meme 时，
      // 继续往下会算出 _.random(0, -1) 再访问 infos[undefined].keywords 直接报错
      await e.reply('暂无可用随机 meme')
      return true
    }
    let index = _.random(0, keys.length - 1, false)
    logger.debug(keys, index)
    e.msg = infos[keys[index]].keywords[0]
    return await this.memes(e)
  }

  /**
     * #memes
     * @param e oicq传递的事件参数e
     */
  async memes(e) {
    if (Config.meme_turnOff) return false;

    // meme响应CD。原来的 GET→SET 两步不是原子的：并发消息可能同时读到空值而一起通过。
    // 改为 SET NX 一步抢占，靠返回值判断是否抢到（node-redis 的 transformReply 会返回 null）。
    const cdKey = `Yz:paimon_meme_cd:${e.group_id}:${e.sender.user_id || e.user_id}`
    const meme_CD = Config.meme_CD
    const bypassCD = !!(e.isFromPaimonChuo || e.isMaster)
    if (meme_CD > 0) {
      if (bypassCD) {
        // 主人 / 被戳：照旧放行，并刷新 CD
        await redis.set(cdKey, 1, { EX: meme_CD })
      } else if (!(await redis.set(cdKey, 1, { NX: true, EX: meme_CD }))) {
        // 抢占失败 = 此前已有 CD
        return false
      }
    } else if (!bypassCD && (await redis.get(cdKey))) {
      // meme_CD 关闭时不再写入新 CD，但**只 GET 不 DEL**：所以残留的 CD 不是"再拦一次"，
      // 而是在它原有 TTL 到期前**每次都拦**（名字叫残留，行为是继续生效）
      return false
    }

    // console.log(e)
    let msg = e.msg.replace('#', '')
    /**
     * 智能匹配最长关键词
     * @param {string} msg 用户消息
     * @param {Object} keyMap 关键词映射对象
     * @returns {string} 匹配到的最长关键词，如果没有匹配则返回null
     */
    function findLongestMatchingKey(msg, keyMap) {
      // 找出所有匹配消息开头的关键词
      const matchingKeys = Object.keys(keyMap).filter(k => msg.startsWith(k));
      if (matchingKeys.length === 0) {
        return null; // 没有匹配项
      }
      // 按关键词长度降序排序，选择最长的一个
      return matchingKeys.sort((a, b) => b.length - a.length)[0];
    }
    // 替换原有的硬编码匹配逻辑
    let target = findLongestMatchingKey(msg, keyMap);

    let targetCode = keyMap[target]
    // let target = e.msg.replace(/^#?meme(s)?/, '')
    let text1 = _.trimStart(e.msg, '#').replace(target, '')
    if (text1.trim() === '详情' || text1.trim() === '帮助') {
      await e.reply(detail(targetCode))
      return true
    }

    // 只按**第一个** `#` 切：裸参数本身也可以含 `#`（例如 string 参数要传 URL 的 fragment
    // `关键词#https://a.com/p#sec`）。split('#') 会把第二个 `#` 之后的内容整个丢掉
    const hashAt = text1.indexOf('#')
    let text = hashAt === -1 ? text1 : text1.slice(0, hashAt)
    let args = hashAt === -1 ? '' : text1.slice(hashAt + 1)
    let formData = new FormData()
    let info = infos[targetCode]
    let fileLoc

    // 提取 @ 信息并获取用户详情缓存
    // 两处防御：① `派蒙戳一戳.js` 是 `new memes().memes(e)` 直接调用，不保证带 message 数组；
    // ② at 段在不同适配器下有 `{type:'at', qq}` 与 `{type:'at', data:{qq}}` 两种形态，
    //    只读 atMsg.qq 会把 undefined 喂进 getUserDetailedInfo，头像变成 `nk=undefined`
    const atMessages = Array.isArray(e.message) ? e.message.filter(m => m.type === 'at') : []
    let atUsers = [];
    for (let atMsg of atMessages) {
      const atQq = atMsg.qq ?? atMsg.data?.qq
      if (atQq === undefined || atQq === null) continue
      let user = await getUserDetailedInfo(e, atQq);
      atUsers.push({
        qq: atQq,
        text: user?.card || atMsg.name || atMsg.text || '',
        gender: user?.gender || 'unknown'
      });
    }
    const hasAt = atUsers.length > 0;

    if (info.params_type.max_images > 0) {
      /**
       * 取图优先级：回复消息 → 本条消息附图 → @对象头像，按缺口逐级补齐。
       * 旧写法是 `if (回复) ... else if (e.img) ... else if (hasAt)`，只要这条是回复就彻底不看
       * 本条图片和 @，于是"回复一条纯文字 + 自己带图"会退化成发送者头像。
       * 目标是补到 max(min_images, 1)：即"至少要有一张真图"（保持旧行为：有真图就不用头像），
       * 同时满足 min_images 的缺口。
       */
      const needImages = Math.max(info.params_type.min_images, 1)
      let imgUrls = []
      if (e.source || e.reply_id) {
        imgUrls.push(...(await getReplyImages(e)))
      }
      if (imgUrls.length < needImages && e.img?.length) {
        // 本条消息一起发的图
        imgUrls.push(...e.img)
      }
      if (imgUrls.length < needImages && hasAt) {
        // 艾特的用户的头像
        imgUrls.push(...atUsers.map(at => `https://q1.qlogo.cn/g?b=qq&s=160&nk=${at.qq}`))
      }
      // 逐级补齐后可能出现同一张图（回复图与本条图相同），去重避免重复喂给同一张 meme
      imgUrls = _.uniq(imgUrls)

      /** 发送者头像。全程按字符串使用——历史上这里被包成 `[url]` 再赋值给 imgUrls[0]，
       *  导致下面的 `imgUrl.startsWith(...)` 抛 `startsWith is not a function` */
      const meAvatar = await getAvatar(e)
      if (!imgUrls || imgUrls.length === 0) {
        // 如果都没有，用发送者的头像
        imgUrls = [meAvatar]
      }
      if (imgUrls.length < info.params_type.min_images && imgUrls.indexOf(meAvatar) === -1) {
        // 如果数量不够，补上发送者头像，且放到最前面
        imgUrls = [meAvatar].concat(imgUrls)
      }

      // 来源就不够：既没带够图、也没 @ 人，而一张发送者头像填不上 min_images >= 2 的缺口。
      // 必须在这里直接说清"要做什么"——否则只能把残缺请求丢给远端，用户看到的是一句服务端校验错
      if (imgUrls.length < info.params_type.min_images) {
        await e.reply(
          `这个表情至少要 ${info.params_type.min_images} 张图片：请发送图片，或 @ 需要出镜的人（会用 TA 的头像）`,
          true
        )
        return true
      }

      logger.debug('imgUrls:', imgUrls)
      if (protectList.includes(targetCode) && masterProtectDo) {
        let masters = await getMasterQQ()
        // 有些meme只需要传一张图，此时如果targetQQ是主人，那meme的人就是他自己
        if (imgUrls.length === 1) {
          if (imgUrls[0].startsWith('https://q1.qlogo.cn')) {
            let split = imgUrls[0].split('=')
            let targetQQ = split[split.length - 1]
            if (masters.map(q => q + '').indexOf(targetQQ) > -1) {
              imgUrls[0] = meAvatar
            }
          }
        } else {
          if (imgUrls[1].startsWith('https://q1.qlogo.cn')) {
            let split = imgUrls[1].split('=')
            let targetQQ = split[split.length - 1]
            if (masters.map(q => q + '').indexOf(targetQQ) > -1) {
              imgUrls = [imgUrls[1], meAvatar]
            }
          }
        }
      }
      imgUrls = imgUrls.slice(0, Math.min(info.params_type.max_images, imgUrls.length))
      for (let i = 0; i < imgUrls.length; i++) {
        let imgUrl = imgUrls[i];
        let buffer;
        let fileType = 'jpeg';
        let mimeType = 'image/jpeg';
        if (imgUrl.startsWith('data:') || imgUrl.startsWith('base64://')) {
          let base64Data = '';
          if (imgUrl.startsWith('data:')) {
            const matches = imgUrl.match(/^data:([^;]+);base64,(.+)$/);
            if (!matches) {
              console.warn(`第 ${i} 个图片格式不正确，跳过`);
              continue;
            }
            mimeType = matches[1];
            // 与 HTTP 下载同口径：只接受图片。否则 `data:text/html;base64,...` 也能混进来
            if (!mimeType.startsWith('image/')) {
              logger.warn(`[meme] 第 ${i + 1} 张 data URI 不是图片(${mimeType})，跳过`);
              continue;
            }
            fileType = mimeType.split('/')[1] || 'jpeg';
            base64Data = matches[2];
          } else {
            base64Data = imgUrl.replace(/^base64:\/\//, '');
          }
          // 先按 base64 长度预估解码后大小，再决定要不要分配内存：
          // Buffer.from 会一次性把整块开出来，只靠最后那次 checkFileSize() 拦不住这步分配
          // 3/4 估算会因 Base64 的 '=' padding 最多高估 2 byte，而 1MB = 1048576 恰好 mod 3 = 1，
          // 于是"实际正好等于上限"的图可能被误判。按 padding 精确扣掉再比
          const padding = base64Data.endsWith('==') ? 2 : base64Data.endsWith('=') ? 1 : 0
          const estimatedSize = Math.floor(base64Data.length * 3 / 4) - padding
          if (estimatedSize > maxFileSizeByte) {
            await e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`);
            return true;
          }
          buffer = Buffer.from(base64Data, 'base64');
        } else {
          // 下载失败/响应异常/不是图片都只跳过这一张：QQ CDN 超时、链接失效、404 的 HTML
          // 页面都不该让整个命令 reject（旧写法 fetch 在最终 try 之外，异常会直接冒出去）
          let imageResponse
          try {
            imageResponse = await fetch(imgUrl, { signal: timeoutSignal(IMAGE_TIMEOUT) })
          } catch (err) {
            logger.warn(`[meme] 第 ${i + 1} 张图片下载失败，跳过: ${hidePrivacyInfo(err.message)}`)
            continue
          }
          if (!imageResponse.ok) {
            logger.warn(`[meme] 第 ${i + 1} 张图片响应异常(${imageResponse.status})，跳过`)
            continue
          }
          const contentType = imageResponse.headers.get('content-type') || ''
          if (!contentType.startsWith('image/')) {
            logger.warn(`[meme] 第 ${i + 1} 张图片 content-type 不是图片(${contentType || '空'})，跳过`)
            continue
          }
          mimeType = contentType.split(';')[0].trim()
          fileType = mimeType.split('/')[1] || 'jpeg'
          // 先看声明长度，避免把超大文件整份读进内存
          const declaredSize = Number(imageResponse.headers.get('content-length')) || 0
          if (declaredSize > maxFileSizeByte) {
            await e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
            return true
          }
          buffer = Buffer.from(await imageResponse.arrayBuffer())
          if (buffer.length > maxFileSizeByte) {
            // 没有 Content-Length 或声明不准时兜底
            await e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
            return true
          }
        }
        formData.append(
          'images',
          new File([buffer], `avatar_${i}.${fileType}`, { type: mimeType })
        );
      }
      const gotImages = formData.getAll('images').length
      if (gotImages < info.params_type.min_images) {
        // 走到这里说明"来源够、但下载失败"：把差几张一起说出来，用户才知道要不要重发
        const missing = info.params_type.min_images - gotImages
        await e.reply(
          `需要 ${info.params_type.min_images} 张图片，其中 ${missing} 张下载失败，请重发图片或检查链接后重试`,
          true
        )
        return true
      }
    }

    if (text && info.params_type.max_texts === 0) {
      return false
    }

    if (!text && info.params_type.min_texts > 0) {
      if (hasAt) {
        text = atUsers[0].text
      } else {
        text = e.sender.card || e.sender.nickname
      }
    }
    // 只有真有文字才提交 texts 字段。`''.split('/', n)` 得到的是 `['']`，而服务端会把空串过滤掉：
    // 净效果等于"显式传了个空文本"，把上游的 default_texts 顶掉——可选文本的模板会渲染成空文字版，
    // 而不是详情页里写的【默认文本】版（旧代码后面那个 nickname 兜底也因此永远进不去，是死逻辑）
    if (text) {
      const texts = text.split('/', info.params_type.max_texts)
      if (texts.length < info.params_type.min_texts) {
        await e.reply(`字不够！要至少${info.params_type.min_texts}个用/隔开！`, true)
        return true
      }
      texts.forEach(t => {
        formData.append('texts', t)
      })
    }

    let userInfos = hasAt ? atUsers : [{ text: e.sender.card || e.sender.nickname, gender: e.sender.sex }]
    args = handleArgs(targetCode, args, userInfos)

    if (args) {
      formData.set('args', args)
    }
    const images = formData.getAll('images')
    if (checkFileSize(images)) {
      // 用入参 e 而不是 this.e：派蒙戳一戳是 `new memes().memes(e)`，那种调用没有 this.e
      return e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
    }

    logger.info('派蒙meme表情制作:\ninput', { target, targetCode, images, texts: formData.getAll('texts'), args: formData.getAll('args') })

    let response
    try {
      response = await fetch(baseUrl + '/memes/' + targetCode + '/', {
        method: 'POST',
        body: formData,
        signal: timeoutSignal(MEME_RENDER_TIMEOUT)
        // headers: {
        // 'Content-Type': 'multipart/form-data'
        // }
      })
    } catch (error) {
      // node-fetch 的 Error.message 会把完整请求 URL 拼进去（`request to http://<ip>:<port>/… failed`），
      // 直接打整个 Error 对象等于把部署机 IP 写进日志
      logger.error('[meme] 请求失败:', hidePrivacyInfo(error.message))
      await e.reply(`[meme]表情制作失败: ${hidePrivacyInfo(error.message)}`, true, { recallMsg: !Config.is_recallMsg ? 0 : 119 })
      return true
    }
    if (response.status > 299) {
      const errText = await response.text()
      // 别用裸 console.error：它绕过日志级别，而且服务端错误正文未经脱敏
      logger.error(`[meme] 服务端返回 ${response.status}:`, hidePrivacyInfo(errText))
      await e.reply(hidePrivacyInfo(errText), true, { recallMsg: !Config.is_recallMsg ? 0 : 119 })
      return true
    }
    // 200 也可能是反代 / WAF / 登录页的 HTML 错页。不校验的话会把 HTML 原样当成图片发给用户
    const outType = response.headers.get('content-type') || ''
    if (!outType.startsWith('image/')) {
      const peek = await response.text()
      logger.error(`[meme] 出图接口返回的不是图片(${outType || '空'}):`, hidePrivacyInfo(peek.slice(0, 300)))
      await e.reply('表情生成失败：服务端返回的不是图片，请稍后重试', true)
      return true
    }
    // mkdirs('data/memes/result')
    // let resultFileLoc = `data/memes/result/${Date.now()}.gif`
    const resultBlob = await response.blob()
    const resultArrayBuffer = await resultBlob.arrayBuffer()
    // const resultBuffer = Buffer.from(resultArrayBuffer)
    // await fs.writeFileSync(resultFileLoc, resultBuffer)
    const resultBase64 = Buffer.from(resultArrayBuffer).toString('base64')
    // await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`), reply)
    await e.reply(segment.image("base64://" + resultBase64), reply)
    // fileLoc && await fs.unlinkSync(fileLoc)
    // await fs.unlinkSync(resultFileLoc)

    // 异步记录 meme 使用次数
    this.recordMemeUsage(targetCode).catch(err => {
      logger.warn('[meme] 记录使用次数失败:', err.message)
    })
  }
}

/**
 * 从一个字段关联的 `parser_options` 里抽出「可输入名 → 值」映射。
 *
 * 只收 `action.type === 0` 的**开关**类 option（`左` / `--left` / `爷` / `--person`）：
 * 非 `-` 前缀的名字原样收；`--xxx` 去掉前缀收。带值的 option（`args[].name` 有值）不参与——
 * 它的名字只用来关联字段，值由用户从 `#` 后给。
 *
 * 关联字段的三种方式任一命中即可：`opt.dest === prop`、`opt.args[].name === prop`、
 * `names` 里含 `--<prop>`。最后这条是必需的——boolean 字段的 option `dest` 常为 null
 * （如 `clown.person` 的 option 只有 `names: ['--person','爷']`），只能靠它认出来。
 *
 * **这个规则只在这里定义一份**：`handleArgs()` 与实际解析、`generateSupportArgsText()` 与
 * 帮助文案都调它。两边各写一套的话，识别结果迟早会漂开（改了一处忘了另一处）。
 * @param {string} prop 字段名
 * @param {Array<object>} parserOptions
 * @returns {Record<string, unknown>} 名字 → 该名字对应的值（可能是 `0` / `false`）
 */
function buildOptionValueMap(prop, parserOptions) {
  const map = {}
  for (const opt of parserOptions) {
    if (opt.action?.type !== 0) continue
    const related =
      opt.dest === prop ||
      (opt.args || []).some(a => a.name === prop) ||
      (opt.names || []).includes(`--${prop}`)
    if (!related) continue
    for (const name of opt.names || []) {
      if (!/^-/.test(name)) map[name] = opt.action.value
      else if (name.startsWith('--')) map[name.slice(2)] = opt.action.value
    }
  }
  return map
}

/**
 * 解析 `<关键词><文本>#<参数>` 里的**单个**参数。
 *
 * ## 协议（插件自定义的子集，不是上游的完整 args 协议）
 * `#` 后只接受一个裸值：`#左` / `#20` / `#0.5`。拿到值后按各字段自己的类型分别处理——
 * 枚举走 `valueMap` 映射（找不到就走 `default`）、数字做整数/范围校验（越界就不传该字段）。
 * 注意合法枚举值可能是 `0`，判断要用 `_.has` 而不是 `||`。
 *
 * ## 支持范围
 * - **单字段模板（55 个）**：一个裸值没有歧义，上游的**基础类型全部支持**——
 *   `enum`、`integer`、`number`、`string`（直接透传，如 `#奖状#2026年9月19日`）、
 *   `boolean`（靠 `parser_options` 的开关名触发，如 `#小丑#爷`、`#摸#圆`）
 * - **多字段模板（只有 5 个）**：**不完整支持**，只沿用旧行为把裸值交给 `enum` / `number` 字段：
 *
 *   | 模板 | 字段 | 现状 |
 *   | --- | --- | --- |
 *   | `ba_say` ba说 | `character`(int) `position`(enum) | 值写给 `character`，`position` 走默认 |
 *   | `pjsk` | `character`(int) `number`(int) | **同一个值写给两个字段** |
 *   | `note_for_leave` 请假条 / `abstinence` 戒导 / `my_wife` 我老婆 | `time` `name` `pronoun`（string） | 参数被丢弃（string 分支只对单字段开放，否则两个字段会被同一个值灌满） |
 *
 * **为什么不加多字段语法**：修它得引入 flag（上游 `parser_options` 里就有 `-t/--time`、`-n/--name`）。
 * 实测评估过一版并**已按要求撤回**——那套写法用户记不住，为 5 个模板把参数协议搞复杂不划算，
 * 所以保持"一个裸值"的最小接口。要加必须连 `generateSupportArgsText()` 一起改。
 *
 * @param {string} key meme 的 key
 * @param {string} args `#` 之后的原始串（可能为空）
 * @param {Array<{text: string, gender: string}>} userInfos @ 到的人，会填进 args.user_infos
 * @returns {string} JSON 字符串，直接作为 multipart 的 args 字段发出
 */
function handleArgs(key, args, userInfos) {
  if (!args) {
    args = ''
  }

  let argsObj = {}

  // 检查是否有参数类型定义
  if (infos[key]?.params_type?.args_type) {
    const argsType = infos[key].params_type.args_type;
    const argsModel = argsType.args_model;
    const parserOptions = argsType.parser_options || [];
    /**
     * 模板是否只有**一个**可配字段。
     * 单字段时"一个裸值"没有任何歧义，可以把上游的基础类型（含 string / boolean）都支持全；
     * 多字段时说不清给谁，只保留旧行为（灌给 enum / number 字段），见 JSDoc 的表格。
     */
    const onlyField = Object.keys(argsModel.properties).filter(p => p !== 'user_infos').length === 1;

    /** `#` 之后的原始值。协议只有一个裸值，所以所有字段共用同一个（在同一处声明，别在各分支里重复声明） */
    const trimmedArg = args.trim();

    // 处理枚举类型参数
    for (const prop in argsModel.properties) {
      if (prop === 'user_infos') continue; // 用户信息单独处理

      const propInfo = argsModel.properties[prop];

      // 查找相关的parser选项
      if (propInfo.enum) {
        // 字段关联规则只在 buildOptionValueMap() 里定义一份。这里别再写第二套条件，
        // 否则'只靠 --<字段名> 关联'的字段会被前置过滤掉、压根进不来
        const valueMap = buildOptionValueMap(prop, parserOptions);
        if (Object.keys(valueMap).length > 0) {
          // 合法枚举值可能是 0/false/''（左右、角度这类正是 0/1），
          // 用 `valueMap[arg] || default` 会把这些合法值吞掉退回默认值
          argsObj[prop] = _.has(valueMap, trimmedArg) ? valueMap[trimmedArg] : propInfo.default;
        }
        continue;
      }
      // 处理数字类型参数
      else if (propInfo.type === 'integer' || propInfo.type === 'number') {
        // number 要接受小数与负数，integer 额外要求是整数；空串不能被 Number() 当成 0
        const numValue = trimmedArg === '' ? NaN : Number(trimmedArg);
        if (Number.isFinite(numValue) && (propInfo.type !== 'integer' || Number.isInteger(numValue))) {
          // 越界就不传该参数（让服务端用自己的默认值），而不是传一个必然被拒的值
          const { minimum, maximum } = propInfo;
          const inRange =
            (minimum === undefined || numValue >= minimum) &&
            (maximum === undefined || numValue <= maximum);
          if (inRange) {
            argsObj[prop] = numValue;
          } else {
            logger.debug(`[meme] 参数 ${prop} = ${numValue} 超出范围 [${minimum}, ${maximum}]，已忽略`);
          }
        }
      }
      // 单字段模板：string 直接透传（`#奖状#2026年9月19日` → time）
      else if (onlyField && propInfo.type === 'string') {
        if (trimmedArg !== '') {
          argsObj[prop] = trimmedArg;
        }
      }
      // 单字段模板：boolean 没有 enum，靠 parser_options 里 action.type === 0 的开关名关联
      // （`#小丑#爷` / `#摸#圆`）。值取 action.value（true），认不出来就不传、走默认 false
      else if (onlyField && propInfo.type === 'boolean') {
        const boolMap = buildOptionValueMap(prop, parserOptions);
        if (_.has(boolMap, trimmedArg)) {
          argsObj[prop] = boolMap[trimmedArg];
        }
      }
    }
  }

  argsObj.user_infos = userInfos.map(u => {
    return {
      name: _.trim(u.text || u.name, '@'),
      gender: u.gender || 'unknown'
    }
  })

  return JSON.stringify(argsObj);
}

const detail = code => {
  let d = infos[code];
  let keywords = d.keywords.join('、');
  let ins = `【代码】${d.key}\n【名称】${keywords}\n【最大图片数量】${d.params_type.max_images}\n【最小图片数量】${d.params_type.min_images}\n【最大文本数量】${d.params_type.max_texts}\n【最小文本数量】${d.params_type.min_texts}\n【默认文本】${d.params_type.default_texts.join('/')}\n`;

  // 检查是否有参数类型定义
  if (d.params_type.args_type?.parser_options?.length > 0) {
    let supportArgs = generateSupportArgsText(d);
    ins += `【支持参数】${supportArgs}`;
  }

  return ins;
};

/**
 * 生成 `#关键词详情` 里的「支持参数」帮助文案。
 *
 * 只描述**一个**字段（循环里碰到第一个业务字段就 return）。范围与 `handleArgs()` 对齐：
 * `enum` / `boolean` 列出可输入的开关名（`可选：圆、circle。如 #圆`）、数字给范围、
 * `string` 给形态示例。开关名同样走 `buildOptionValueMap()`，与解析侧共用一套规则。
 *
 * 多字段 `args_model` 本就不完整支持（见 `handleArgs()` 的表格），所以文案也只讲第一个，
 * 不假装支持多个。将来若真要加多字段语法，这里必须改成逐字段列出。
 * @param {object} info meme 的 info
 * @returns {string}
 */
function generateSupportArgsText(info) {
  try {
    const argsType = info.params_type.args_type;
    const props = argsType.args_model.properties;
    const options = argsType.parser_options;

    // 只描述第一个业务字段 —— 与 handleArgs() 的处理范围一致
    for (const prop in props) {
      if (prop === 'user_infos') continue;

      const propInfo = props[prop];
      const option = options.find(opt =>
        opt.dest === prop ||
        (opt.args && opt.args.some(arg => arg.name === prop))
      );
      const description = option?.help_text || propInfo.description || prop;

      // 开关名映射：enum 与 boolean 共用同一套规则（buildOptionValueMap），
      // 否则帮助文案和实际解析会各认一套名字
      const switchNames = Object.keys(buildOptionValueMap(prop, options));
      if ((propInfo.enum || propInfo.type === 'boolean') && switchNames.length > 0) {
        // 示例优先给中文名 —— 用户实际要打的就是它（`#万花筒#圆`）
        const example = switchNames.find(n => !/^[a-z]/i.test(n)) || switchNames[0];
        return `${description}，可选：${switchNames.join('、')}。如 #${example}`;
      }

      if (propInfo.type === 'integer' || propInfo.type === 'number') {
        let rangeText = '';
        if (propInfo.minimum !== undefined && propInfo.maximum !== undefined) {
          rangeText = `范围为${propInfo.minimum}~${propInfo.maximum}`;
        } else if (propInfo.description && propInfo.description.includes('范围')) {
          rangeText = propInfo.description;
        }
        return `${description}${rangeText ? '，' + rangeText : ''}。如 #1`;
      }

      // string：值直接透传，给个形态示例
      if (propInfo.type === 'string') {
        // 时间/日期类字段给日期示例，其它（名字、二维码内容…）给通用示例
        const example = /时间|日期/.test(`${prop}${description}`) ? '#2026年9月19日' : '#示例文字';
        return `${description}，直接跟文字。如 ${example}`;
      }

      return `${description}参数`;
    }

    return '支持额外参数';
  } catch (e) {
    console.error(`生成参数说明出错: ${hidePrivacyInfo(e.message)}`);
    return '支持额外参数';
  }
}

// 最大支持的文件大小（字节）
const maxFileSizeByte = maxFileSize * 1024 * 1024

// 如果有任意一个文件大于 maxSize，则返回true
function checkFileSize(files) {
  let fileList = Array.isArray(files) ? files : [files]
  fileList = fileList.filter(file => !!(file?.size))
  if (fileList.length === 0) {
    return false
  }
  // 用 > 而不是 >=：文案是"最多支持 N MB"，恰好等于上限应当算合法。
  // 网络下载那两条检查用的也是 >，三处必须同口径
  return fileList.some(file => file.size > maxFileSizeByte)
}

function mkdirs(dirname) {
  if (fs.existsSync(dirname)) {
    return true
  } else {
    if (mkdirs(path.dirname(dirname))) {
      fs.mkdirSync(dirname)
      return true
    }
  }
}

async function getMasterQQ() {
  return (await import('../../../lib/config/config.js')).default.masterQQ
}

async function getAvatar(e, userId = e.sender.user_id) {
  if (typeof e.getAvatarUrl === 'function') {
    return await e.getAvatarUrl(0)
  }
  return `https://q1.qlogo.cn/g?b=qq&s=0&nk=${userId}`
}

/**
 * 取被回复消息里的图片 url。
 * - 兼容 oicq 的 `e.getReply()` 与 onebot 的 `getChatHistory` 两种取历史消息的方式
 * - 用入参 `e` 而不是 `this.e`：`派蒙戳一戳.js` 是 `new memes().memes(e)` 直接调用的，那种场景没有 `this.e`
 * @param {object} e
 * @returns {Promise<string[]>}
 */
async function getReplyImages(e) {
  let reply
  if (e.getReply) {
    reply = await e.getReply()
  } else if (e.source) {
    if (e.group?.getChatHistory) reply = (await e.group.getChatHistory(e.source.seq, 1)).pop()
    else if (e.friend?.getChatHistory) reply = (await e.friend.getChatHistory(e.source.time, 1)).pop()
  }
  if (!Array.isArray(reply?.message)) return []
  return reply.message.filter(v => v.type === 'image' && v.url).map(v => v.url)
}

/**
 * 单个远端请求的超时时间（毫秒）。
 * 没有超时的话，连接卡住时根本进不到下一次重试，插件数据会长时间停留在待更新状态。
 */
const REQUEST_TIMEOUT = 15000

/** 图片下载超时（毫秒）。图片体积大，给得比 JSON 请求宽松一点 */
const IMAGE_TIMEOUT = 20000

/**
 * 出图请求超时（毫秒）：POST /memes/<key>/ 生成、以及远端 /memes/render_list。
 * 生成 GIF 天生慢，不能复用 REQUEST_TIMEOUT 的 15s；但也不能不设——远端连接挂住时
 * `await fetch` 会无限 pending，用户那条命令就永远不返回。
 */
const MEME_RENDER_TIMEOUT = 120000

/**
 * 生成超时中断信号（node-fetch 3.x 支持 `signal`）。
 * `AbortSignal.timeout` 需要 Node >= 17.3，低版本退回 AbortController + setTimeout。
 * @param {number} ms
 * @returns {AbortSignal}
 */
function timeoutSignal(ms) {
  if (typeof AbortSignal?.timeout === 'function') return AbortSignal.timeout(ms)
  const controller = new AbortController()
  setTimeout(() => controller.abort(), ms).unref?.()
  return controller.signal
}

/**
 * 安全解析 JSON 响应。
 * - 非 200 / 非 JSON content-type / 解析失败一律返回 null，避免被 HTML 错误页炸到外层
 * - 注意：response 只能消费一次，调用方拿到结果后不能再用该 response
 */
async function safeJson(response) {
  if (!response || response.status !== 200) return null
  const ct = response.headers.get('content-type') || ''
  if (!ct.toLowerCase().includes('json')) return null
  try {
    return await response.json()
  } catch {
    return null
  }
}

/** `fetchMemeInfo()` 的返回值之一：服务端明确答复该 key 不存在，与"请求失败"区分开 */
const MEME_NOT_FOUND = Symbol('meme-not-found')

/**
 * 校验一份「infos + keyMap」数据集是否可用。三道关：
 *
 * 1. **正向**：keyMap 的每个目标都得是真实存在的 meme，且该 meme 的关键词表里真有这个关键词
 *    （挡住外部数据凭空塞进来的"额外触发词"——它会被注册成命令）
 * 2. **反向**：infos 里每个 meme 的**每个**关键词都必须能在 keyMap 里找到条目（截断信号）。
 *    注意**只查存在性、不查归属**：关键词可以跨 meme 重复（实测 15 个），而 keyMap 一个关键词
 *    只能有一个目标，要求"回指自己"会把合法数据判死
 * 3. **params_type**：见 `badParamsType()`。命令层直接读这些字段，外面数据缺了它，
 *    要等到用户真发命令才在 `info.params_type.max_images` 处炸掉
 * @param {unknown} infos
 * @param {unknown} keyMap
 * @returns {{ ok: boolean, reason: string }} 不通过时 reason 说明首个原因（写日志用）
 */
function validateMemeDataset(infos, keyMap) {
  if (!infos || typeof infos !== 'object' || Array.isArray(infos)) return { ok: false, reason: 'infos 不是对象' }
  if (!keyMap || typeof keyMap !== 'object' || Array.isArray(keyMap)) return { ok: false, reason: 'keyMap 不是对象' }

  const infoKeys = Object.keys(infos)
  if (infoKeys.length === 0) return { ok: false, reason: 'infos 为空' }
  if (Object.keys(keyMap).length === 0) return { ok: false, reason: 'keyMap 为空' }

  // 正向：每个关键词既要指向真实存在的 meme，**还要真的属于它**。
  // 只查"目标存在"是不够的：外部数据可以塞一个 infos 里根本没有的额外触发词，
  // 而 memeKeyRules() 会把它直接注册成命令——等于凭空多出一个消息路由入口。
  // 配上反向那条（每个 infos 关键词都回指自己），合起来就是严格的 1:1
  for (const [keyword, target] of Object.entries(keyMap)) {
    // 必须用 Object.hasOwn：直接 `infos[target]` 会从 Object.prototype 取到 `toString` /
    // `constructor` 这类 truthy 值，于是下一句 `infos[target].keywords` 直接 TypeError ——
    // 等于校验器被脏输入打崩，和它存在的目的正好相反
    if (!Object.hasOwn(infos, target)) {
      return { ok: false, reason: `关键词「${keyword}」指向不存在的 meme「${target}」` }
    }
    if (!infos[target].keywords.includes(keyword)) {
      return { ok: false, reason: `关键词「${keyword}」不属于 meme「${target}」` }
    }
  }

  // 反向：infos 里每个 meme 的**每个**关键词都必须在 keyMap 里有条目——这才是"keyMap 被截断"的信号。
  //
  // 但**不能**要求 `keyMap[keyword] === memeKey`（回指自己）：实测 971 个 meme 里有 **15 个关键词被
  // ≥2 个 meme 声明**（「嗦」同时属于 suck 和 kou、「口」同时属于 oral_sex 和 kou、「跳舞」同时属于
  // stickman_dancing 和 tiaowu_mao……），而一个关键词在 keyMap 里只能有一个目标，必然有一方
  // "回指不到自己"。曾经按严格 1:1 写过一版，结果逐项重建出的**合法**数据被整批判不合法，
  // `#表情包更新` 直接失败（14 个关键词触发）——所以这里只查"存在性"，不查归属
  for (const [memeKey, info] of Object.entries(infos)) {
    for (const keyword of info.keywords) {
      if (!Object.hasOwn(keyMap, keyword)) {
        return {
          ok: false,
          reason: `关键词「${keyword}」（属于 meme「${memeKey}」）在 keyMap 里没有条目，数据集疑似被截断`,
        }
      }
    }
  }

  // params_type 也要守：外面数据缺了它，直到用户真发命令才在 `info.params_type.max_images` 处炸掉
  for (const [memeKey, info] of Object.entries(infos)) {
    const bad = badParamsType(info.params_type)
    if (bad) return { ok: false, reason: `meme「${memeKey}」的 ${bad}` }
  }

  return { ok: true, reason: '' }
}

/**
 * 校验 `params_type` 的最小 schema。合法返回 null，否则返回一句原因。
 * 命令层直接读 `params_type.min_images` / `default_texts`，缺字段要在进门时挡住，
 * 而不是等命令执行到一半再抛 TypeError。
 * @param {unknown} p
 * @returns {string|null}
 */
function badParamsType(p) {
  if (!p || typeof p !== 'object' || Array.isArray(p)) return 'params_type 缺失或不是对象'
  for (const field of ['min_images', 'max_images', 'min_texts', 'max_texts']) {
    const v = p[field]
    if (!Number.isInteger(v) || v < 0) return `params_type.${field} 不是非负整数（${JSON.stringify(v)}）`
  }
  if (p.min_images > p.max_images) return 'params_type.min_images > max_images'
  if (p.min_texts > p.max_texts) return 'params_type.min_texts > max_texts'
  if (!Array.isArray(p.default_texts)) return 'params_type.default_texts 不是数组'

  // args_type 也要守。只校验外层的话，`args_type: {}` 能通过，
  // 等用户真触发命令才在 `Object.keys(argsModel.properties)` 处抛 TypeError
  const at = p.args_type
  if (at !== null && at !== undefined) {
    if (typeof at !== 'object' || Array.isArray(at)) return 'params_type.args_type 不是对象'
    const model = at.args_model
    if (!model || typeof model !== 'object' || Array.isArray(model)) {
      return 'params_type.args_type.args_model 缺失或不是对象'
    }
    const props = model.properties
    if (!props || typeof props !== 'object' || Array.isArray(props)) {
      return 'params_type.args_type.args_model.properties 缺失或不是对象'
    }
    const opts = at.parser_options
    if (opts !== null && opts !== undefined && !Array.isArray(opts)) {
      return 'params_type.args_type.parser_options 不是数组'
    }
    // 容器类型对了还不够，还得守住**里面的节点**：`properties.foo = null` 或
    // `parser_options = [null]` 都能通过容器检查，而 handleArgs() 会直接
    // `propInfo.enum` / `opt.action?.type` 解引用，等于 validator 被脏输入打崩
    for (const [name, prop] of Object.entries(props)) {
      if (!prop || typeof prop !== 'object' || Array.isArray(prop)) {
        return `params_type.args_type.args_model.properties.${name} 不是对象`
      }
    }
    for (const opt of opts || []) {
      if (!opt || typeof opt !== 'object' || Array.isArray(opt)) {
        return 'params_type.args_type.parser_options 里有非对象项'
      }
      if (opt.args !== null && opt.args !== undefined && !Array.isArray(opt.args)) {
        return 'params_type.args_type.parser_options[].args 不是数组'
      }
      // 数组元素也要查：`args: [null]` 能过"是数组"这关，但 buildOptionValueMap() 里
      // `(opt.args || []).some(a => a.name === prop)` 会直接解引用 null 抛 TypeError ——
      // 这就是"脏输入必须守到真正解引用节点"的最后一个缺口
      for (const arg of opt.args || []) {
        if (!arg || typeof arg !== 'object' || Array.isArray(arg)) {
          return 'params_type.args_type.parser_options[].args 里有非对象项'
        }
        if (arg.name !== undefined && typeof arg.name !== 'string') {
          return 'params_type.args_type.parser_options[].args[].name 不是字符串'
        }
      }
      if (opt.names !== null && opt.names !== undefined && !Array.isArray(opt.names)) {
        return 'params_type.args_type.parser_options[].names 不是数组'
      }
      for (const name of opt.names || []) {
        if (typeof name !== 'string') {
          return 'params_type.args_type.parser_options[].names 里有非字符串项'
        }
      }
    }
  }
  return null
}

/**
 * 读取本地缓存数据集。
 *
 * infos 与 keyMap 存在**同一个文件**里（见 `MEME_CACHE_FILE` 的说明），所以读取时不存在
 * "两份文件来自不同代"的问题；剩下的风险只是单个文件残缺/被手工改过，交给校验兜住。
 *
 * @returns {{ infos: Record<string, object>, keyMap: Record<string, string> } | null}
 *          读取失败或校验不过时返回 null——调用方据此转为"去拉远端"，这就是冷启动自愈
 */
function loadMemeDataset() {
  let raw
  try {
    if (!fs.existsSync(MEME_CACHE_FILE)) {
      // dataset.json 不存在，可能是刚从旧版升级上来 —— 试一次迁移，别把完好的旧缓存白扔
      return migrateLegacyDataset()
    }
    raw = JSON.parse(fs.readFileSync(MEME_CACHE_FILE, 'utf-8'))
  } catch (e) {
    logger.warn(`[meme] 本地缓存 ${MEME_CACHE_FILE} 读取/解析失败，将从远端重新拉取:`, e.message)
    // 顺手删掉坏文件，免得每次启动都重复报一次。删不掉也无所谓（下次同样会被解析失败挡下），
    // 所以这里的 catch 是**有意的静默**，不是漏写的错误处理
    try { fs.unlinkSync(MEME_CACHE_FILE) } catch { /* 有意忽略：best-effort 清理坏缓存 */ }
    return null
  }

  if (raw?.v !== MEME_CACHE_VERSION) {
    logger.warn(`[meme] 本地缓存版本不符（${raw?.v} != ${MEME_CACHE_VERSION}），将从远端重新拉取`)
    return null
  }

  // 缓存也可能被手工改过或跨版本残留，同样过归一化 + 校验，不能当可信输入
  const infos = sanitizeInfos(raw.infos)
  const keyMap = sanitizeKeyMap(raw.keyMap)
  const verdict = validateMemeDataset(infos, keyMap)
  if (!verdict.ok) {
    logger.warn(`[meme] 本地缓存不可用（${verdict.reason}），将从远端重新拉取`)
    return null
  }
  return { infos, keyMap }
}

/**
 * 从旧版的双文件缓存迁移一次（`infos.json` + `keyMap.json` → `dataset.json`）。
 *
 * 新版只认单文件缓存。如果没有这一步，**刚升级那一次远端恰好不可用**时会把两份仍然完好的
 * 旧缓存一起无视掉，冷启动 `oldKeyMap` 又是空的，整套 meme 直接变不可用——
 * 这与"远端挂了仍能沿用本地缓存"的目标直接冲突。校验通过才迁移并删旧文件，不通过就当作没缓存。
 * @returns {{ infos: Record<string, object>, keyMap: Record<string, string> } | null}
 */
function migrateLegacyDataset() {
  const readLegacy = file => {
    try {
      if (!fs.existsSync(file)) return null
      return JSON.parse(fs.readFileSync(file, 'utf-8'))
    } catch (e) {
      logger.warn(`[meme] 旧缓存 ${file} 读取/解析失败，忽略:`, e.message)
      return null
    }
  }

  const rawInfos = readLegacy(LEGACY_INFOS_FILE)
  const rawKeyMap = readLegacy(LEGACY_KEYMAP_FILE)
  if (!rawInfos || !rawKeyMap) return null

  const infos = sanitizeInfos(rawInfos)
  const keyMap = sanitizeKeyMap(rawKeyMap)
  const verdict = validateMemeDataset(infos, keyMap)
  if (!verdict.ok) {
    logger.warn(`[meme] 旧缓存不可用（${verdict.reason}），忽略`)
    return null
  }

  // 只有新缓存**确实写成功**才删旧文件、才报"已迁移"。
  // saveMemeDataset() 会把写盘失败吞成一句日志，若不看返回值就往下删，
  // 就会变成"新缓存没落盘 + 旧缓存被删 + 下次启动远端又挂了 = 无任何可用数据"
  if (!saveMemeDataset(infos, keyMap)) {
    logger.warn('[meme] 新缓存写入失败，保留旧版 infos.json / keyMap.json 备下次使用')
    return { infos, keyMap }
  }

  logger.mark('[meme] 已把旧版 infos.json / keyMap.json 迁移为 dataset.json')
  for (const file of [LEGACY_INFOS_FILE, LEGACY_KEYMAP_FILE]) {
    // 迁移完就删，免得下次启动再走一遍；删不掉也无所谓，上面的校验会兜住
    try { fs.unlinkSync(file) } catch { /* best-effort */ }
  }
  return { infos, keyMap }
}
/**
 * 落盘缓存数据集。
 *
 * 先写 `.tmp` 再 `rename`，**不要**直接 `writeFileSync` 到目标：后者会先截断目标文件，
 * 写盘中途崩溃/断电就留下半个 JSON；若下次启动远端也挂了，最后一份可用缓存就没了。
 * 同一分区内的 rename 是原子的，和整条刷新链路"数据备齐再提交"的思路一致。
 * @param {Record<string, object>} infos
 * @param {Record<string, string>} keyMap
 * @returns {boolean} 是否真的写成功。**调用方必须看返回值**：
 *          比如旧缓存迁移要靠它决定"能不能删旧文件"，吞掉失败就会丢掉最后一份可用缓存
 */
function saveMemeDataset(infos, keyMap) {
  const tmp = `${MEME_CACHE_FILE}.tmp`
  try {
    fs.writeFileSync(tmp, JSON.stringify({ v: MEME_CACHE_VERSION, savedAt: Date.now(), infos, keyMap }))
    fs.renameSync(tmp, MEME_CACHE_FILE)
    return true
  } catch (err) {
    logger.warn('[meme] 写入本地缓存失败:', err.message)
    try { fs.unlinkSync(tmp) } catch { /* best-effort 清理临时文件 */ }
    return false
  }
}

/**
 * 拉单个 meme 的 info，带有限重试。
 * 逐项重建里"任何一条失败整批作废"，所以单条值得重试；次数不能大，否则 971 条乘起来会拖很久。
 * @param {string} key
 * @returns {Promise<object | symbol | null>} info / MEME_NOT_FOUND（404）/ null（失败）
 */
async function fetchMemeInfo(key) {
  for (let i = 0; i <= REBUILD_ITEM_RETRIES; i++) {
    try {
      const res = await fetch(`${baseUrl}/memes/${key}/info`, { signal: timeoutSignal(REQUEST_TIMEOUT) })
      // 404 是确定性答复（服务端没有这个 key），交给调用方按"跳过"处理
      if (res.status === 404) return MEME_NOT_FOUND
      // 其它确定性 4xx（401/403/400…）重试同样没意义：/keys 能通但 /info 全 401 时
      // 会对每个 key 白跑三轮。与 fetchJsonWithRetry 的口径保持一致
      if (res.status >= 400 && res.status < 500 && res.status !== 408 && res.status !== 429) return null
      const info = await safeJson(res)
      if (info && Array.isArray(info.keywords)) return info
    } catch (e) {
      logger.debug(`[meme] 拉取 ${key} 的 info 失败 (第${i + 1}次): ${hidePrivacyInfo(e.message)}`)
    }
    if (i < REBUILD_ITEM_RETRIES) await new Promise(r => setTimeout(r, 300 * (i + 1)))
  }
  return null
}

/**
 * 用 `/memes/keys` + 逐个 `/memes/<key>/info` 重建数据集（原生上游没有聚合接口时的兜底）。
 *
 * 两处是刻意设计：
 * - **并发**：971 个 key 串行请求按平均 150ms 要 ~146s，还叠加每条 15s 超时的最坏情况。
 *   这里用固定数量 worker 分批跑，既快又不会一次性打爆后端。
 * - **严格性**：逐项重建很容易只成功一部分，所以要求"除 404 之外全部成功"，否则会用
 *   "300 个里成功 2 个"的残缺数据顶掉原有完整数据，还对外报更新成功。**404 单独放行**是因为
 *   它是确定性答复而非瞬时失败——把它算作失败的话，只要有一个 key 数据漂移，插件就永远无法更新。
 *
 * @param {string[]} keys
 * @returns {Promise<{ infos: Record<string, object>, keyMap: Record<string, string> } | null>}
 *          未达完整性要求时返回 null
 */
async function rebuildFromKeys(keys) {
  const infos = {}
  const keyMap = {}
  /** 服务端明确答复"不存在"的 key，不计入失败 */
  const missing = []
  const failed = []
  let cursor = 0

  const worker = async () => {
    while (cursor < keys.length) {
      const key = keys[cursor++]
      const info = await fetchMemeInfo(key)
      if (info === MEME_NOT_FOUND) { missing.push(key); continue }
      if (!info) { failed.push(key); continue }
      // 关键词过一遍归一化：空关键词会注册出 `cmdReg('')` 这种劫持消息路由的规则
      const keywords = normalizeKeywords(info.keywords)
      keywords.forEach(keyword => {
        keyMap[keyword] = key
      })
      infos[key] = { ...info, keywords }
    }
  }

  await Promise.all(Array.from({ length: Math.min(REBUILD_CONCURRENCY, keys.length) }, worker))

  if (failed.length) {
    logger.warn(
      `[meme] 逐项重建不完整（成功 ${Object.keys(infos).length}、服务端不存在 ${missing.length}、请求失败 ${failed.length}，共 ${keys.length}），丢弃本次结果`
    )
    return null
  }
  if (missing.length) {
    logger.warn(
      `[meme] 逐项重建：${missing.length} 个 key 在服务端不存在，已跳过（例：${missing.slice(0, 5).join('、')}）`
    )
  }
  return { infos, keyMap }
}

/**
 * 归一化外部数据里的关键词：只留非空字符串。
 *
 * 空关键词（`''` 或纯空白）会生成 `new RegExp('^#?')` 这种几乎匹配一切消息的规则，
 * 动态注册之后等于把消息路由劫持掉，所以外部数据进门时必须先过这一关。
 * 注意这里**只过滤，不因为过滤后为空就把整条目丢掉**——条目本身要留在 infos 里，
 * 否则 keyMap 指向它会触发"数据不一致"整批作废，反而把插件卡在永不更新。
 * @param {unknown} keywords
 * @returns {string[]}
 */
function normalizeKeywords(keywords) {
  if (!Array.isArray(keywords)) return []
  return keywords.filter(kw => typeof kw === 'string' && kw.trim() !== '')
}

/**
 * 归一化「关键词 → memeKey」映射：键必须是非空字符串，值必须是非空字符串。
 * @param {unknown} raw
 * @returns {Record<string, string>}
 */
function sanitizeKeyMap(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return {}
  // 无原型对象：外部数据里的 `__proto__` 键在普通 `{}` 上会走原型 setter 而不是写成 own property，
  // 这正是原型污染最常见的入口。`Object.create(null)` 让所有键都只是普通数据
  const out = Object.create(null)
  for (const [keyword, key] of Object.entries(raw)) {
    if (typeof keyword === 'string' && keyword.trim() !== '' && typeof key === 'string' && key !== '') {
      out[keyword] = key
    }
  }
  return out
}

/**
 * 归一化 infos：丢掉非对象条目，把每个条目的 keywords 过滤一遍。
 * 同样返回无原型对象，理由见 `sanitizeKeyMap()`。
 * @param {unknown} raw
 * @returns {Record<string, object>}
 */
function sanitizeInfos(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return {}
  const out = Object.create(null)
  for (const [key, info] of Object.entries(raw)) {
    if (!info || typeof info !== 'object') continue
    out[key] = { ...info, keywords: normalizeKeywords(info.keywords) }
  }
  return out
}

/**
 * 带重试的 JSON 拉取。
 * 远端（如 HF Space）偶发超时或响应截断，infos.json 已超过 300KB，单次失败概率不低。
 * 单次请求带超时，否则连接卡住时重试永远不会发生。
 * @param {string} url
 * @param {number} retries 最大尝试次数
 * @returns {Promise<any|null>} 失败返回 null，不抛错
 */
async function fetchJsonWithRetry(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url, { signal: timeoutSignal(REQUEST_TIMEOUT) })
      // 永久失败（4xx，408/429 除外）当场放弃，别重试：
      // /memes/static/*.json 在纯上游必定 404，重试只换来 1s+2s 的退避白等，且必然再失败
      if (res.status >= 400 && res.status < 500 && res.status !== 408 && res.status !== 429) {
        logger.debug(`[meme] 拉取 ${hidePrivacyInfo(url)} 返回 ${res.status}，判定为永久失败，不再重试`)
        return null
      }
      const data = await safeJson(res)
      if (data) return data
      logger.warn(`[meme] 拉取 ${hidePrivacyInfo(url)} 返回非预期内容 (第${i + 1}次)`)
    } catch (e) {
      logger.warn(`[meme] 拉取 ${hidePrivacyInfo(url)} 失败 (第${i + 1}次): ${hidePrivacyInfo(e.message)}`)
    }
    if (i < retries - 1) {
      await new Promise(r => setTimeout(r, 1000 * (i + 1)))
    }
  }
  return null
}
