// 同步时间：2024年12月29日
// 源码地址：https://github.com/ikechan8370/yunzai-meme/blob/main/meme.js

import plugin from '../../../lib/plugins/plugin.js';
import fetch, { File, FormData } from 'node-fetch'
import fs from 'fs'
import path from 'node:path'
import _ from 'lodash'
import loader from '../../../lib/plugins/loader.js'
import { Config } from '../utils/config.js'
import {
  hidePrivacyInfo,
  getUserDetailedInfo,
} from '../utils/paimonFuction.js'

if (!global.segment) {
  global.segment = (await import('oicq')).segment
}
const baseUrl = Config.meme_baseUrl
/**
 * 机器人发表情是否引用回复用户
 * @type {boolean}
 */
const reply = Config.meme_reply
/**
 * 是否强制使用#触发命令
 */
const forceSharp = Config.meme_forceSharp
/**
 * 主人保护，撅主人时会被反撅 (暂时只支持QQ)
 * @type {boolean}
 */
const masterProtectDo = Config.meme_masterProtectDo
/**
 * 用户输入的图片，最大支持的文件大小，单位为MB
 * @type {number}
 */
const maxFileSize = Config.meme_maxFileSize

let keyMap = {}

let infos = {}

/**
 * 主人保护list 如['lash','do','beat_up','little_do']
 */
let protectList = ['lash', 'do', 'beat_up', 'little_do', 'fast_do', 'qi', 'fast_qi']

/**
 * meme 使用计数 Redis key 前缀
 */
const MEME_USAGE_REDIS_PREFIX = 'Yz:paimon_meme_usage:'

/**
 * 本插件在云崽插件加载器中的 key（file.name）后缀，用于定位已注册的插件条目
 */
const PLUGIN_FILE_NAME = '派蒙meme.js'

/**
 * 命令前缀：forceSharp 开启时强制要求 `#`。
 * 基础命令与 meme 关键词命令共用同一套前缀，避免"开了强制 # 但 `meme列表` 仍能不带 # 触发"的不一致
 */
const cmdReg = body => new RegExp(`${forceSharp ? '^#' : '^#?'}${body}`)

/**
 * 基础命令规则（不依赖 keyMap，插件加载后即生效）
 */
const baseRules = () => [
  { /** 命令正则匹配 */ reg: cmdReg('(meme(s)?|表情包)列表$'), /** 执行方法 */ fnc: 'memesList' },
  { reg: cmdReg('随机(meme(s)?|表情包)'), fnc: 'randomMemes' },
  { reg: cmdReg('(meme(s)?|表情包)帮助'), fnc: 'memesHelp' },
  { reg: cmdReg('(meme(s)?|表情包)搜索'), fnc: 'memesSearch' },
  { reg: cmdReg('(meme(s)?|表情包)更新'), fnc: 'memesUpdate', permission: 'master' }
]

/**
 * 依据当前 keyMap 生成 meme 关键词规则
 *
 * 关键词必须按**字面量**匹配：`memes()` 内部是用 `msg.startsWith(k)` 找目标的。
 * 不转义的话，含 `(` `[` `\` 的关键词会让 `new RegExp` 直接抛错（整批规则构造失败），
 * 含 `.` `+` `*` 的会误匹配（如 `a.b` 命中 `aXb`，而 `memes()` 又按字面量找不到 → 后续取 info 报错）。
 * @returns {Array<{reg: RegExp, fnc: string}>}
 */
const memeKeyRules = () =>
  Object.keys(keyMap).map(key => ({
    /** 命令正则匹配 */
    reg: cmdReg(_.escapeRegExp(key)),
    /** 执行方法 */
    fnc: 'memes'
  }))

export class memes extends plugin {
  constructor() {
    let option = {
      /** 功能名称 */
      name: '派蒙meme表情制作',
      /** 功能描述 */
      dsc: '派蒙meme表情制作',
      /** https://oicqjs.github.io/oicq/#events */
      event: 'message',
      /** 优先级，数字越小等级越高 */
      priority: 5000,
      /** 基础规则 + 当前已加载到的 meme 关键词规则 */
      rule: [...baseRules(), ...memeKeyRules()]
    }

    super(option)

    // generated by ChatGPT
    function generateCronExpression() {
      // 生成每天的半夜2-4点之间的小时值（随机选择）
      const hour = Math.floor(Math.random() * 3) + 2

      // 生成每小时的随机分钟值（0到59之间的随机数）
      const minute = Math.floor(Math.random() * 60)

      // 构建 cron 表达式
      return `${minute} ${hour} * * *`
    }

    this.task = {
      // 每天的凌晨3点执行
      cron: generateCronExpression(),
      name: 'memes自动更新任务',
      /** 传 true 表示忽略本地缓存，强制拉取远端（否则定时任务只会把本地缓存重新读一遍，等于空转） */
      fnc: this.init.bind(this, true)
    }
  }

  /**
   * 初始化 / 更新 meme 资源，并把最新规则同步到插件加载器
   *
   * 关键约束：`infos`/`keyMap` 是命令处理时直接读的全局状态。整次拉取都在**局部变量**里完成，
   * 只有拿到一份完整且互相一致的数据才一次性替换（原子提交）。
   * 旧实现一进来就清空全局再去 await 网络，而加载器里旧关键词规则仍然生效，
   * 更新期间命中旧关键词就会拿到空 keyMap / undefined info 直接报错。
   *
   * @param {boolean} force true 时忽略本地缓存强制拉取远端，用于手动更新与定时任务
   * @returns {Promise<{ refreshed: boolean, keys: number, fallback: boolean }>}
   *          refreshed: 本次是否拿到可用的远端数据；keys: 最终生效的关键词数量；
   *          fallback: 拉取失败后是否沿用了更新前的数据
   */
  async init(force = false) {
    mkdirs('data/memes')
    /** 更新前的数据，拉取失败时用于回退 */
    const oldKeyMap = keyMap
    const oldInfos = infos

    // 本地缓存读取，文件损坏也不要炸
    const readJsonFile = (file) => {
      try {
        if (fs.existsSync(file)) {
          return JSON.parse(fs.readFileSync(file, 'utf-8'))
        }
      } catch (e) {
        logger.warn(`[meme] 本地缓存 ${file} 读取/解析失败，将忽略:`, e.message)
        try { fs.unlinkSync(file) } catch { }
      }
      return {}
    }

    /** 本次结果先落局部变量，校验通过才替换全局 */
    let nextInfos = {}
    let nextKeyMap = {}
    /**
     * 是否真的从远端取到了数据并被采纳（区别于"只是读了本地缓存"）。
     * 只在远端赋值处置真，否则插件每次启动都会误报"更新完成"并清掉列表图缓存。
     */
    let fetched = false

    if (force) {
      // 强制刷新：跳过本地缓存，让下面的远端拉取分支一定执行
      logger.mark('yunzai-meme 强制更新：忽略本地缓存，直接拉取远端')
    } else {
      // 插件加载：优先用本地缓存，避免启动被远端拖慢
      nextInfos = readJsonFile('data/memes/infos.json')
      nextKeyMap = readJsonFile('data/memes/keyMap.json')
    }

    // 远端拉取失败不应阻塞插件加载（HF Space 等已下线时这里会全失败）
    try {
      if (!baseUrl) {
        throw new Error('meme_baseUrl 未配置')
      }
      // /memes/static/infos.json、keyMap.json 只是可选加速，不是上游 meme-generator 的接口：
      // 上游 app.py 只有 /memes/keys、/memes/<key>/info、/memes/render_list 等，直连会 404；
      // 只有少数部署额外加了这层聚合（如 qwqcc HF Space 的 bootstrap.py 动态生成）。
      // 所以拿不到时必须保底重建（见下方逐项重建分支）。
      if (Object.keys(nextInfos).length === 0) {
        logger.mark('yunzai-meme infos资源本地不存在，正在远程拉取中')
        const data = await fetchJsonWithRetry(`${baseUrl}/memes/static/infos.json`)
        if (data && Object.keys(data).length) {
          nextInfos = data
          fetched = true
        }
      }
      if (Object.keys(nextKeyMap).length === 0) {
        logger.mark('yunzai-meme keyMap资源本地不存在，正在远程拉取中')
        const data = await fetchJsonWithRetry(`${baseUrl}/memes/static/keyMap.json`)
        if (data && Object.keys(data).length) {
          nextKeyMap = data
          fetched = true
        }
      }

      if (Object.keys(nextInfos).length === 0 || Object.keys(nextKeyMap).length === 0) {
        // 两个静态资源拿不齐，才退回逐项重建
        logger.warn('[meme] 静态资源拉取失败（判断为原生 meme 生成器），切换为逐项重建兜底：从 /memes/keys 取 key 列表，再逐个请求 /memes/<key>/info 重建 keyMap 与 infos')
        const keys = await fetchJsonWithRetry(`${baseUrl}/memes/keys`)
        if (Array.isArray(keys) && keys.length) {
          const keyMapTmp = {}
          const infosTmp = {}
          for (const key of keys) {
            const keyInfoRes = await fetch(`${baseUrl}/memes/${key}/info`, {
              signal: timeoutSignal(REQUEST_TIMEOUT)
            })
            const info = await safeJson(keyInfoRes)
            if (info && Array.isArray(info.keywords)) {
              info.keywords.forEach(keyword => {
                keyMapTmp[keyword] = key
              })
              infosTmp[key] = info
            }
          }
          // 逐项重建很容易只成功一部分：覆盖不全就整批丢弃。
          // 否则会用"300 个里成功 2 个"的残缺数据顶掉原有完整数据，还对外报更新成功
          if (Object.keys(infosTmp).length >= keys.length) {
            nextInfos = infosTmp
            nextKeyMap = keyMapTmp
            fetched = true
          } else {
            logger.warn(
              `[meme] 逐项重建不完整（成功 ${Object.keys(infosTmp).length}/${keys.length}），丢弃本次结果`
            )
            nextInfos = {}
            nextKeyMap = {}
            fetched = false
          }
        }
      }
    } catch (err) {
      logger.warn('[meme] 远程拉取 meme 资源失败，插件仍可加载但功能将不可用:', err.message)
    }

    /** 数据必须成对且互相一致：keyMap 里每个 memeKey 都要能在 infos 里找到 */
    const consistent = Object.values(nextKeyMap).every(key => nextInfos[key])
    const usable = Object.keys(nextInfos).length > 0 && Object.keys(nextKeyMap).length > 0 && consistent
    if (!usable && Object.keys(nextKeyMap).length > 0) {
      logger.warn('[meme] infos 与 keyMap 不一致或残缺，放弃本次拉取结果')
    }

    const refreshed = usable && fetched
    let fallback = false
    if (usable) {
      // 原子替换：命令处理读到的要么是旧数据、要么是新数据，不会是半套
      infos = nextInfos
      keyMap = nextKeyMap
      if (fetched) {
        try {
          fs.writeFileSync('data/memes/infos.json', JSON.stringify(infos))
          fs.writeFileSync('data/memes/keyMap.json', JSON.stringify(keyMap))
        } catch (err) {
          logger.warn('[meme] 写入本地缓存失败:', err.message)
        }
      }
    } else if (Object.keys(oldKeyMap).length > 0) {
      // 没拿到可用数据时沿用更新前的数据，别把正在用的 meme 全部弄没
      infos = oldInfos
      keyMap = oldKeyMap
      fallback = true
      logger.warn('[meme] 未取到新数据，继续沿用更新前的 meme 资源')
    } else {
      // 冷启动且拉取失败：保持空，规则交给 registerRules 兜底
      infos = {}
      keyMap = {}
    }

    if (refreshed) {
      // 数据变了，列表图（24h 缓存）也该重渲染
      this.clearRenderListCache()
      logger.mark(`[meme] 更新完成，共 ${Object.keys(keyMap).length} 个 meme 关键词`)
    }

    // 手动/自动更新都会走到这里：把最新规则同步回加载器，免重启生效
    this.registerRules()

    return { refreshed, keys: Object.keys(keyMap).length, fallback }
  }

  /** 清理 meme 列表图缓存（memesList 的 24h 缓存），下次查看时重新渲染 */
  clearRenderListCache() {
    const file = 'data/memes/render_list.jpg'
    if (fs.existsSync(file)) {
      try {
        fs.unlinkSync(file)
      } catch (err) {
        logger.warn('[meme] 清理列表图缓存失败:', err.message)
      }
    }
  }

  /**
   * 生成当前应生效的完整规则（基础规则 + keyMap 关键词规则）
   * @returns {Array<{reg: RegExp, fnc: string, permission?: string}>}
   */
  getRules() {
    return [...baseRules(), ...memeKeyRules()].map(rule => ({
      ...rule,
      reg: rule.reg instanceof RegExp ? rule.reg : new RegExp(rule.reg)
    }))
  }

  /**
   * 把最新规则注册/更新到云崽插件加载器
   *
   * `PluginsLoader.deal()` 匹配命令时读取的是 loader.priority 里**注册实例**的 rule，
   * 每次消息执行时 new 出来的实例只是副本，改副本的 rule 不生效，
   * 所以必须回写注册条目，才能在 init()（手动 #meme更新 / 定时任务自动更新）之后立即生效。
   *
   * 插件加载阶段调用 init() 时本插件尚未 push 进 priority，此时匹配不到条目属正常情况，
   * 随后的注册实例会由构造函数按当时已就绪的 keyMap 生成规则。
   * @returns {number} 被同步的注册条目数
   */
  registerRules() {
    if (Object.keys(keyMap).length === 0) {
      // 远端拉取失败时不要清空规则，保留旧规则继续可用
      logger.warn('[meme] keyMap 为空，跳过规则同步，保留原有 meme 命令')
      return 0
    }

    const rules = this.getRules()
    this.rule = rules

    const entries = loader.priority.filter(
      i => i.class === memes || (typeof i.key === 'string' && i.key.endsWith(PLUGIN_FILE_NAME))
    )
    for (const entry of entries) {
      if (!entry.plugin) continue
      entry.plugin.rule = rules
    }

    if (entries.length) {
      logger.mark(`[meme] 已动态注册 ${Object.keys(keyMap).length} 个 meme 关键词规则`)
    } else {
      logger.debug('[meme] 插件尚未注册到加载器，规则将由注册时的构造函数生成')
    }
    return entries.length
  }

  async memesUpdate(e) {
    await e.reply('yunzai-memes更新中')
    let result
    try {
      // 强制刷新，不再依赖「先删缓存文件」来触发远端拉取
      result = await this.init(true)
    } catch (err) {
      await e.reply('更新失败：' + hidePrivacyInfo(err.message))
      return
    }
    if (result.fallback) {
      await e.reply(`更新失败：未拉取到新资源，继续沿用原有 ${result.keys} 个 meme 规则`)
    } else if (!result.refreshed) {
      await e.reply('更新失败：未拉取到 meme 资源，已保留原有规则')
    } else {
      await e.reply(`更新完成，已注册 ${result.keys} 个 meme 规则`)
    }
  }

  async memesHelp(e) {
    if (Config.meme_turnOff) return false;
    e.reply('【memes列表】：查看支持的memes列表\n【{表情名称}】：memes列表中的表情名称，根据提供的文字或图片制作表情包\n【随机meme】：随机制作一些表情包\n【meme搜索+关键词】：搜索表情包关键词\n【{表情名称}+详情】：查看该表情所支持的参数')
  }

  async memesSearch(e) {
    if (Config.meme_turnOff) return false;
    let search = e.msg.replace(/^#?(meme(s)?|表情包)搜索/, '').trim()
    if (!search) {
      await e.reply('你要搜什么？')
      return true
    }
    let hits = Object.keys(keyMap).filter(k => k.indexOf(search) > -1)
    let result = '搜索结果'
    if (hits.length > 0) {
      for (let i = 0; i < hits.length; i++) {
        result += `\n${i + 1}. ${hits[i]}`
      }
    } else {
      result += '\n无'
    }
    await e.reply(result, e.isGroup)
  }

  async memesList(e) {
    if (Config.meme_turnOff) return false

    const resultFileLoc = 'data/memes/render_list.jpg'
    const cacheMaxAge = 24 * 60 * 60 * 1000 // 24小时缓存

    // 检查缓存是否有效
    if (fs.existsSync(resultFileLoc)) {
      const stats = fs.statSync(resultFileLoc)
      if (Date.now() - stats.mtimeMs < cacheMaxAge) {
        await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`))
        return true
      }
    }

    // 构建带标签和排序的 meme 列表
    const memeList = await this.buildMemeListWithLabels()

    const response = await fetch(`${baseUrl}/memes/render_list`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        meme_list: memeList,
        text_template: '{keywords}',
        add_category_icon: true
      })
    })

    if (!response.ok) {
      logger.error('[meme] render_list 请求失败:', response.status)
      return false
    }

    const resultBlob = await response.blob()
    const resultBuffer = Buffer.from(await resultBlob.arrayBuffer())
    fs.writeFileSync(resultFileLoc, resultBuffer)
    await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`))
    return true
  }

  /**
   * 构建带标签的 meme 列表（按创建时间倒序,便于观察新增的表情）
   * - new: 最近30天内创建
   * - hot: 期限内使用超过30次
   * @returns {Promise<Array<{meme_key: string, disabled: boolean, labels: string[]}>>}
   */
  async buildMemeListWithLabels() {
    const NEW_THRESHOLD_MS = 30 * 24 * 60 * 60 * 1000 // 30天
    const HOT_THRESHOLD = 30 // 使用次数阈值
    const now = Date.now()

    // 批量获取所有 meme 的使用计数
    const memeKeys = Object.keys(infos)
    const usageCounts = await this.getMemeUsageCounts(memeKeys)

    return Object.entries(infos)
      .map(([key, info]) => {
        const createdTime = new Date(info.date_created).getTime()
        const labels = []

        if ((now - createdTime) < NEW_THRESHOLD_MS) labels.push('new')
        if ((usageCounts[key] || 0) >= HOT_THRESHOLD) labels.push('hot')

        return { meme_key: key, disabled: false, labels, _sortKey: createdTime }
      })
      .sort((a, b) => b._sortKey - a._sortKey)
      .map(({ meme_key, disabled, labels }) => ({ meme_key, disabled, labels }))
  }

  /**
   * 批量获取 meme 使用计数（只返回有使用记录的）
   * @param {string[]} memeKeys - meme key 列表
   * @returns {Promise<Record<string, number>>} - { meme_key: count }（仅包含 count > 0 的）
   */
  async getMemeUsageCounts(memeKeys) {
    const counts = {}

    if (memeKeys.length === 0) return counts

    const redisKeys = memeKeys.map(key => `${MEME_USAGE_REDIS_PREFIX}${key}`)
    try {
      const results = await redis.mGet(redisKeys)
      memeKeys.forEach((key, index) => {
        const count = parseInt(results[index]) || 0
        if (count > 0) counts[key] = count  // 只存非零值
      })
    } catch (err) {
      logger.warn('[meme] 批量获取使用计数失败:', err.message)
    }

    return counts
  }

  /**
   * 记录 meme 使用次数（3天过期，每次使用重置过期时间）
   * @param {string} memeKey - meme 的 key
   */
  async recordMemeUsage(memeKey) {
    const REDIS_KEY = `${MEME_USAGE_REDIS_PREFIX}${memeKey}`
    const EXPIRE_SECONDS = 3 * 24 * 60 * 60 // 3天

    // INCR + EXPIRE 保证计数增加并重置过期时间
    await redis.incr(REDIS_KEY)
    await redis.expire(REDIS_KEY, EXPIRE_SECONDS)
  }

  /**
   * @description: 
   * @param {*} e
   * @param {*} isDeleteUnharmoniousKeys 是否删除的不和谐的 keys，默认为 false;
   * @return {*}
   */
  async randomMemes(e, isDeleteUnharmoniousKeys = false) {
    if (Config.meme_turnOff) return false;
    let keys = Object.keys(infos).filter(key => infos[key].params_type.min_images === 1 && infos[key].params_type.min_texts === 0)
    if (isDeleteUnharmoniousKeys) {
      /** 需要删除的不和谐的 keys */
      const keys_delete = ['behead', 'tomb_yeah', 'shishilani', 'thump_wildly', 'clown', 'taunt', 'mourning', 'rise_dead'];
      keys = keys.filter(key => !keys_delete.includes(key));
    }
    if (!keys.length) {
      // 远端数据没拉到、或某个版本里没有"只要一张图"的 meme 时，
      // 继续往下会算出 _.random(0, -1) 再访问 infos[undefined].keywords 直接报错
      await e.reply('暂无可用随机 meme')
      return true
    }
    let index = _.random(0, keys.length - 1, false)
    logger.debug(keys, index)
    e.msg = infos[keys[index]].keywords[0]
    return await this.memes(e)
  }

  /**
     * #memes
     * @param e oicq传递的事件参数e
     */
  async memes(e) {
    if (Config.meme_turnOff) return false;

    // meme响应CD。原来的 GET→SET 两步不是原子的：并发消息可能同时读到空值而一起通过。
    // 改为 SET NX 一步抢占，靠返回值判断是否抢到（node-redis 的 transformReply 会返回 null）。
    const cdKey = `Yz:paimon_meme_cd:${e.group_id}:${e.sender.user_id || e.user_id}`
    const meme_CD = Config.meme_CD
    const bypassCD = !!(e.isFromPaimonChuo || e.isMaster)
    if (meme_CD > 0) {
      if (bypassCD) {
        // 主人 / 被戳：照旧放行，并刷新 CD
        await redis.set(cdKey, 1, { EX: meme_CD })
      } else if (!(await redis.set(cdKey, 1, { NX: true, EX: meme_CD }))) {
        // 抢占失败 = 此前已有 CD
        return false
      }
    } else if (!bypassCD && (await redis.get(cdKey))) {
      // meme_CD 关闭时沿用旧行为：残留在 key 上的 CD 仍然拦一次，只是不再写入
      return false
    }

    // console.log(e)
    let msg = e.msg.replace('#', '')
    /**
     * 智能匹配最长关键词
     * @param {string} msg 用户消息
     * @param {Object} keyMap 关键词映射对象
     * @returns {string} 匹配到的最长关键词，如果没有匹配则返回null
     */
    function findLongestMatchingKey(msg, keyMap) {
      // 找出所有匹配消息开头的关键词
      const matchingKeys = Object.keys(keyMap).filter(k => msg.startsWith(k));
      if (matchingKeys.length === 0) {
        return null; // 没有匹配项
      }
      // 按关键词长度降序排序，选择最长的一个
      return matchingKeys.sort((a, b) => b.length - a.length)[0];
    }
    // 替换原有的硬编码匹配逻辑
    let target = findLongestMatchingKey(msg, keyMap);

    let targetCode = keyMap[target]
    // let target = e.msg.replace(/^#?meme(s)?/, '')
    let text1 = _.trimStart(e.msg, '#').replace(target, '')
    if (text1.trim() === '详情' || text1.trim() === '帮助') {
      await e.reply(detail(targetCode))
      return true
    }

    let [text, args = ''] = text1.split('#')
    let formData = new FormData()
    let info = infos[targetCode]
    let fileLoc

    // 提取 @ 信息并获取用户详情缓存
    const atMessages = e.message.filter(m => m.type === 'at');
    let atUsers = [];
    for (let atMsg of atMessages) {
      let user = await getUserDetailedInfo(e, atMsg.qq);
      atUsers.push({
        qq: atMsg.qq,
        text: user?.card || atMsg.name || atMsg.text || '',
        gender: user?.gender || 'unknown'
      });
    }
    const hasAt = atUsers.length > 0;

    if (info.params_type.max_images > 0) {
      /**
       * 取图优先级：回复消息 → 本条消息附图 → @对象头像，按缺口逐级补齐。
       * 旧写法是 `if (回复) ... else if (e.img) ... else if (hasAt)`，只要这条是回复就彻底不看
       * 本条图片和 @，于是"回复一条纯文字 + 自己带图"会退化成发送者头像。
       * 目标是补到 max(min_images, 1)：即"至少要有一张真图"（保持旧行为：有真图就不用头像），
       * 同时满足 min_images 的缺口。
       */
      const needImages = Math.max(info.params_type.min_images, 1)
      let imgUrls = []
      if (e.source || e.reply_id) {
        imgUrls.push(...(await getReplyImages(e)))
      }
      if (imgUrls.length < needImages && e.img?.length) {
        // 本条消息一起发的图
        imgUrls.push(...e.img)
      }
      if (imgUrls.length < needImages && hasAt) {
        // 艾特的用户的头像
        imgUrls.push(...atUsers.map(at => `https://q1.qlogo.cn/g?b=qq&s=160&nk=${at.qq}`))
      }
      // 逐级补齐后可能出现同一张图（回复图与本条图相同），去重避免重复喂给同一张 meme
      imgUrls = _.uniq(imgUrls)

      /** 发送者头像。全程按字符串使用——历史上这里被包成 `[url]` 再赋值给 imgUrls[0]，
       *  导致下面的 `imgUrl.startsWith(...)` 抛 `startsWith is not a function` */
      const meAvatar = await getAvatar(e)
      if (!imgUrls || imgUrls.length === 0) {
        // 如果都没有，用发送者的头像
        imgUrls = [meAvatar]
      }
      if (imgUrls.length < info.params_type.min_images && imgUrls.indexOf(meAvatar) === -1) {
        // 如果数量不够，补上发送者头像，且放到最前面
        imgUrls = [meAvatar].concat(imgUrls)
      }

      logger.debug('imgUrls:', imgUrls)
      if (protectList.includes(targetCode) && masterProtectDo) {
        let masters = await getMasterQQ()
        // 有些meme只需要传一张图，此时如果targetQQ是主人，那meme的人就是他自己
        if (imgUrls.length === 1) {
          if (imgUrls[0].startsWith('https://q1.qlogo.cn')) {
            let split = imgUrls[0].split('=')
            let targetQQ = split[split.length - 1]
            if (masters.map(q => q + '').indexOf(targetQQ) > -1) {
              imgUrls[0] = meAvatar
            }
          }
        } else {
          if (imgUrls[1].startsWith('https://q1.qlogo.cn')) {
            let split = imgUrls[1].split('=')
            let targetQQ = split[split.length - 1]
            if (masters.map(q => q + '').indexOf(targetQQ) > -1) {
              imgUrls = [imgUrls[1], meAvatar]
            }
          }
        }
      }
      imgUrls = imgUrls.slice(0, Math.min(info.params_type.max_images, imgUrls.length))
      for (let i = 0; i < imgUrls.length; i++) {
        let imgUrl = imgUrls[i];
        let buffer;
        let fileType = 'jpeg';
        let mimeType = 'image/jpeg';
        if (imgUrl.startsWith('data:') || imgUrl.startsWith('base64://')) {
          let base64Data = '';
          if (imgUrl.startsWith('data:')) {
            const matches = imgUrl.match(/^data:([^;]+);base64,(.+)$/);
            if (!matches) {
              console.warn(`第 ${i} 个图片格式不正确，跳过`);
              continue;
            }
            mimeType = matches[1];
            fileType = mimeType.split('/')[1] || 'jpeg';
            base64Data = matches[2];
          } else {
            base64Data = imgUrl.replace(/^base64:\/\//, '');
          }
          buffer = Buffer.from(base64Data, 'base64');
        } else {
          // 下载失败/响应异常/不是图片都只跳过这一张：QQ CDN 超时、链接失效、404 的 HTML
          // 页面都不该让整个命令 reject（旧写法 fetch 在最终 try 之外，异常会直接冒出去）
          let imageResponse
          try {
            imageResponse = await fetch(imgUrl, { signal: timeoutSignal(IMAGE_TIMEOUT) })
          } catch (err) {
            logger.warn(`[meme] 第 ${i + 1} 张图片下载失败，跳过: ${hidePrivacyInfo(err.message)}`)
            continue
          }
          if (!imageResponse.ok) {
            logger.warn(`[meme] 第 ${i + 1} 张图片响应异常(${imageResponse.status})，跳过`)
            continue
          }
          const contentType = imageResponse.headers.get('content-type') || ''
          if (!contentType.startsWith('image/')) {
            logger.warn(`[meme] 第 ${i + 1} 张图片 content-type 不是图片(${contentType || '空'})，跳过`)
            continue
          }
          mimeType = contentType.split(';')[0].trim()
          fileType = mimeType.split('/')[1] || 'jpeg'
          // 先看声明长度，避免把超大文件整份读进内存
          const declaredSize = Number(imageResponse.headers.get('content-length')) || 0
          if (declaredSize > maxFileSizeByte) {
            await e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
            return true
          }
          buffer = Buffer.from(await imageResponse.arrayBuffer())
          if (buffer.length > maxFileSizeByte) {
            // 没有 Content-Length 或声明不准时兜底
            await e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
            return true
          }
        }
        formData.append(
          'images',
          new File([buffer], `avatar_${i}.${fileType}`, { type: mimeType })
        );
      }
      if (formData.getAll('images').length < info.params_type.min_images) {
        // 需要的图全部下载失败时给个明确回复，别把残缺请求丢给远端再报一堆看不懂的错
        await e.reply('图片获取失败，请重发图片或检查链接后重试', true)
        return true
      }
    }

    if (text && info.params_type.max_texts === 0) {
      return false
    }

    if (!text && info.params_type.min_texts > 0) {
      if (hasAt) {
        text = atUsers[0].text
      } else {
        text = e.sender.card || e.sender.nickname
      }
    }
    let texts = text.split('/', info.params_type.max_texts)
    if (texts.length < info.params_type.min_texts) {
      await e.reply(`字不够！要至少${info.params_type.min_texts}个用/隔开！`, true)
      return true
    }
    texts.forEach(t => {
      formData.append('texts', t)
    })

    if (info.params_type.max_texts > 0 && formData.getAll('texts').length === 0) {
      if (hasAt) {
        formData.append('texts', atUsers[0].text)
      } else {
        formData.append('texts', e.sender.card || e.sender.nickname)
      }
    }

    let userInfos = hasAt ? atUsers : [{ text: e.sender.card || e.sender.nickname, gender: e.sender.sex }]
    args = handleArgs(targetCode, args, userInfos)

    if (args) {
      formData.set('args', args)
    }
    const images = formData.getAll('images')
    if (checkFileSize(images)) {
      return this.e.reply(`文件大小超出限制，最多支持${maxFileSize}MB`)
    }

    logger.info('派蒙meme表情制作:\ninput', { target, targetCode, images, texts: formData.getAll('texts'), args: formData.getAll('args') })

    let response
    try {
      response = await fetch(baseUrl + '/memes/' + targetCode + '/', {
        method: 'POST',
        body: formData
        // headers: {
        // 'Content-Type': 'multipart/form-data'
        // }
      })
    } catch (error) {
      logger.error('[meme]请求失败:', error)
      await e.reply(`[meme]表情制作失败: ${hidePrivacyInfo(error.message)}`, true, { recallMsg: !Config.is_recallMsg ? 0 : 119 })
      return true
    }
    // console.log(response.status)
    if (response.status > 299) {
      let error = await response.text()
      console.error(error)
      await e.reply(hidePrivacyInfo(error), true, { recallMsg: !Config.is_recallMsg ? 0 : 119 })
      return true
    }
    // mkdirs('data/memes/result')
    // let resultFileLoc = `data/memes/result/${Date.now()}.gif`
    const resultBlob = await response.blob()
    const resultArrayBuffer = await resultBlob.arrayBuffer()
    // const resultBuffer = Buffer.from(resultArrayBuffer)
    // await fs.writeFileSync(resultFileLoc, resultBuffer)
    const resultBase64 = Buffer.from(resultArrayBuffer).toString('base64')
    // await e.reply(segment.image(`${process.cwd()}/${resultFileLoc}`), reply)
    await e.reply(segment.image("base64://" + resultBase64), reply)
    // fileLoc && await fs.unlinkSync(fileLoc)
    // await fs.unlinkSync(resultFileLoc)

    // 异步记录 meme 使用次数
    this.recordMemeUsage(targetCode).catch(err => {
      logger.warn('[meme] 记录使用次数失败:', err.message)
    })
  }
}

function handleArgs(key, args, userInfos) {
  if (!args) {
    args = ''
  }

  let argsObj = {}

  // 检查是否有参数类型定义
  if (infos[key]?.params_type?.args_type) {
    const argsType = infos[key].params_type.args_type;
    const argsModel = argsType.args_model;
    const parserOptions = argsType.parser_options || [];

    // 处理枚举类型参数
    for (const prop in argsModel.properties) {
      if (prop === 'user_infos') continue; // 用户信息单独处理

      const propInfo = argsModel.properties[prop];

      // 查找相关的parser选项
      const relatedOptions = parserOptions.filter(opt =>
        opt.dest === prop ||
        (opt.args && opt.args.some(arg => arg.name === prop))
      );

      if (propInfo.enum && relatedOptions.length > 0) {
        // 为枚举类型创建映射表
        const valueMap = {};

        // 从parser options中提取名称映射
        relatedOptions.forEach(opt => {
          if (opt.action?.type === 0) {
            opt.names.forEach(name => {
              // 处理非选项形式(如"左", "右")和选项形式(如"--right")
              if (!/^-/.test(name)) {
                valueMap[name] = opt.action.value;
              } else if (name.startsWith('--')) {
                // 处理选项形式，去掉前缀--
                const simpleName = name.substring(2);
                valueMap[simpleName] = opt.action.value;
              }
            });
          }
        });

        // 设置默认值。注意合法枚举值可能是 0/false/''（左右、角度这类正是 0/1），
        // 用 `valueMap[arg] || default` 会把这些合法值吞掉退回默认值
        const trimmedArg = args.trim();
        argsObj[prop] = _.has(valueMap, trimmedArg) ? valueMap[trimmedArg] : propInfo.default;
      }
      // 处理数字类型参数
      else if (propInfo.type === 'integer' || propInfo.type === 'number') {
        const trimmedArg = args.trim();
        // number 要接受小数与负数，integer 额外要求是整数；空串不能被 Number() 当成 0
        const numValue = trimmedArg === '' ? NaN : Number(trimmedArg);
        if (Number.isFinite(numValue) && (propInfo.type !== 'integer' || Number.isInteger(numValue))) {
          // 越界就不传该参数（让服务端用自己的默认值），而不是传一个必然被拒的值
          const { minimum, maximum } = propInfo;
          const inRange =
            (minimum === undefined || numValue >= minimum) &&
            (maximum === undefined || numValue <= maximum);
          if (inRange) {
            argsObj[prop] = numValue;
          } else {
            logger.debug(`[meme] 参数 ${prop} = ${numValue} 超出范围 [${minimum}, ${maximum}]，已忽略`);
          }
        }
      }
    }
  }

  argsObj.user_infos = userInfos.map(u => {
    return {
      name: _.trim(u.text || u.name, '@'),
      gender: u.gender || 'unknown'
    }
  })

  return JSON.stringify(argsObj);
}

const detail = code => {
  let d = infos[code];
  let keywords = d.keywords.join('、');
  let ins = `【代码】${d.key}\n【名称】${keywords}\n【最大图片数量】${d.params_type.max_images}\n【最小图片数量】${d.params_type.min_images}\n【最大文本数量】${d.params_type.max_texts}\n【最小文本数量】${d.params_type.min_texts}\n【默认文本】${d.params_type.default_texts.join('/')}\n`;

  // 检查是否有参数类型定义
  if (d.params_type.args_type?.parser_options?.length > 0) {
    let supportArgs = generateSupportArgsText(d);
    ins += `【支持参数】${supportArgs}`;
  }

  return ins;
};

// 辅助函数：根据infos生成参数说明文本
function generateSupportArgsText(info) {
  try {
    const argsType = info.params_type.args_type;
    const props = argsType.args_model.properties;
    const options = argsType.parser_options;

    // 寻找主要参数及其描述
    let mainParam = '';
    let description = '';

    for (const prop in props) {
      if (prop !== 'user_infos') {
        const propInfo = props[prop];
        mainParam = prop;

        // 寻找参数说明
        const option = options.find(opt =>
          opt.dest === prop ||
          (opt.args && opt.args.some(arg => arg.name === prop))
        );

        if (option?.help_text) {
          description = option.help_text;
        } else if (propInfo.description) {
          description = propInfo.description;
        }

        // 如果是枚举类型，列出可能的值
        if (propInfo.enum) {
          // 枚举值可能是 0/false/''，不能用 truthy 判断过滤，否则这些合法值不会出现在说明里
          const isEnumOption = opt => opt.action?.type === 0 && opt.action?.value !== undefined && opt.dest === prop;

          // 收集中文参数名称（非选项形式）
          const chineseNames = options
            .filter(isEnumOption)
            .flatMap(opt => opt.names.filter(name => !/^-/.test(name)));

          // 收集英文参数名称（从选项形式提取）
          const englishNames = options
            .filter(isEnumOption)
            .flatMap(opt => opt.names
              .filter(name => name.startsWith('--'))
              .map(name => name.substring(2))
            );

          // 合并中文和英文参数名称
          const valueNames = [...new Set([...chineseNames, ...englishNames])];

          if (valueNames.length > 0) {
            const valuesText = valueNames.join('、');
            // 优先使用中文名称作为示例
            const exampleName = chineseNames.length > 0 ? chineseNames[0] : valueNames[0];
            return `${description || prop}，可选值：${valuesText}。如#${exampleName}`;
          }
        }
        // 处理数字类型
        else if (propInfo.type === 'integer' || propInfo.type === 'number') {
          // 添加数字范围说明（如果有）
          let rangeText = '';
          if (propInfo.minimum !== undefined && propInfo.maximum !== undefined) {
            rangeText = `范围为${propInfo.minimum}~${propInfo.maximum}`;
          } else if (propInfo.description && propInfo.description.includes('范围')) {
            rangeText = propInfo.description;
          }

          return `${description || prop}${rangeText ? '，' + rangeText : ''}。如#1`;
        }

        break;
      }
    }

    return description || `${mainParam}参数`;

  } catch (e) {
    console.error(`生成参数说明出错: ${hidePrivacyInfo(e.message)}`);
    return '支持额外参数';
  }
}

// 最大支持的文件大小（字节）
const maxFileSizeByte = maxFileSize * 1024 * 1024

// 如果有任意一个文件大于 maxSize，则返回true
function checkFileSize(files) {
  let fileList = Array.isArray(files) ? files : [files]
  fileList = fileList.filter(file => !!(file?.size))
  if (fileList.length === 0) {
    return false
  }
  return fileList.some(file => file.size >= maxFileSizeByte)
}

function mkdirs(dirname) {
  if (fs.existsSync(dirname)) {
    return true
  } else {
    if (mkdirs(path.dirname(dirname))) {
      fs.mkdirSync(dirname)
      return true
    }
  }
}

async function getMasterQQ() {
  return (await import('../../../lib/config/config.js')).default.masterQQ
}

async function getAvatar(e, userId = e.sender.user_id) {
  if (typeof e.getAvatarUrl === 'function') {
    return await e.getAvatarUrl(0)
  }
  return `https://q1.qlogo.cn/g?b=qq&s=0&nk=${userId}`
}

/**
 * 取被回复消息里的图片 url。
 * - 兼容 oicq 的 `e.getReply()` 与 onebot 的 `getChatHistory` 两种取历史消息的方式
 * - 用入参 `e` 而不是 `this.e`：`派蒙戳一戳.js` 是 `new memes().memes(e)` 直接调用的，那种场景没有 `this.e`
 * @param {object} e
 * @returns {Promise<string[]>}
 */
async function getReplyImages(e) {
  let reply
  if (e.getReply) {
    reply = await e.getReply()
  } else if (e.source) {
    if (e.group?.getChatHistory) reply = (await e.group.getChatHistory(e.source.seq, 1)).pop()
    else if (e.friend?.getChatHistory) reply = (await e.friend.getChatHistory(e.source.time, 1)).pop()
  }
  if (!Array.isArray(reply?.message)) return []
  return reply.message.filter(v => v.type === 'image' && v.url).map(v => v.url)
}

/**
 * 单个远端请求的超时时间（毫秒）。
 * 没有超时的话，连接卡住时根本进不到下一次重试，插件数据会长时间停留在待更新状态。
 */
const REQUEST_TIMEOUT = 15000

/** 图片下载超时（毫秒）。图片体积大，给得比 JSON 请求宽松一点 */
const IMAGE_TIMEOUT = 20000

/**
 * 生成超时中断信号（node-fetch 3.x 支持 `signal`）。
 * `AbortSignal.timeout` 需要 Node >= 17.3，低版本退回 AbortController + setTimeout。
 * @param {number} ms
 * @returns {AbortSignal}
 */
function timeoutSignal(ms) {
  if (typeof AbortSignal?.timeout === 'function') return AbortSignal.timeout(ms)
  const controller = new AbortController()
  setTimeout(() => controller.abort(), ms).unref?.()
  return controller.signal
}

/**
 * 安全解析 JSON 响应。
 * - 非 200 / 非 JSON content-type / 解析失败一律返回 null，避免被 HTML 错误页炸到外层
 * - 注意：response 只能消费一次，调用方拿到结果后不能再用该 response
 */
async function safeJson(response) {
  if (!response || response.status !== 200) return null
  const ct = response.headers.get('content-type') || ''
  if (!ct.toLowerCase().includes('json')) return null
  try {
    return await response.json()
  } catch {
    return null
  }
}

/**
 * 带重试的 JSON 拉取。
 * 远端（如 HF Space）偶发超时或响应截断，infos.json 已超过 300KB，单次失败概率不低。
 * 单次请求带超时，否则连接卡住时重试永远不会发生。
 * @param {string} url
 * @param {number} retries 最大尝试次数
 * @returns {Promise<any|null>} 失败返回 null，不抛错
 */
async function fetchJsonWithRetry(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url, { signal: timeoutSignal(REQUEST_TIMEOUT) })
      const data = await safeJson(res)
      if (data) return data
      logger.warn(`[meme] 拉取 ${hidePrivacyInfo(url)} 返回非预期内容 (第${i + 1}次)`)
    } catch (e) {
      logger.warn(`[meme] 拉取 ${hidePrivacyInfo(url)} 失败 (第${i + 1}次): ${e.message}`)
    }
    if (i < retries - 1) {
      await new Promise(r => setTimeout(r, 1000 * (i + 1)))
    }
  }
  return null
}
